### ISSUE TITLE
Slow requests

### ISSUE THREAD

**Issue by kierandrewett** [powercord-org/powercord#102]
**Describe the bug**
Discord is making slow XHR requests after powercord is injected.

**To Reproduce**
Perform any behaviour, and requests become slow.

**Expected behavior**
Fast Instant request

**Desktop (please complete the following information):**
 - OS: Windows
 - Discord version: idk where this is.

**Additional context**
N/A

**Comment by cyyynthia** [comment]
This is not related to Powercord, Discord is having issues atm https://status.discordapp.com/incidents/j13tlh8g4hkq

If this still occurs after the outage, please let me know! :)

**Comment by kierandrewett** [comment]
Thanks! I always forget about their status website. 😆
