### ISSUE TITLE
When disabling plugins that have a setting option in the sidebar, it duplicates the setting

### ISSUE THREAD

**Issue by DonovanDMC** [powercord-org/powercord#103]
**Describe the bug**
When you disable a plugin that has a settings tab, it duplicates the setting tab

**To Reproduce**
Disable a plugin, hastebin for example, settings tab duplicates

**Expected behavior**
Settings tab doesn't duplicate

**Desktop (please complete the following information):**
 - OS: Windows
 - Discord version: I have no clue where you're wanting me to go here, I'm taking what control panel is giving me `0.0.232` (Latest Canary)

**Additional context**
![img588_discordcanary_2019-02-12_23-29-15 701](https://user-images.githubusercontent.com/17226394/52689210-ffe17200-2f1e-11e9-8125-8a80fa4a6b62.png)

**Comment by cyyynthia** [comment]
Probably because hastebin didn't implemented unload properly, poke @aetheryx
