### ISSUE TITLE
Discord not starting after installation

### ISSUE THREAD

**Issue by ferpykins** [powercord-org/powercord#104]
**Describe the bug**
After doing all of the installation steps and attempting to start discord back up, it comes up with a javascript error (attached)

**To Reproduce**
Steps to reproduce the behavior: Install. I guess.

**Expected behavior**
Work???

**Desktop (please complete the following information):**
 - OS: Windows 10 V. 1809
 - Discord version: 32158
 `powercord.buildInfo`

**Additional context**
![image](https://user-images.githubusercontent.com/35282681/52743403-90f82d80-2f9f-11e9-91e6-46cfbf809cf5.png)

**Comment by aetheryx** [comment]
Can you open Windows Explorer and try to find `C:/Windows/System32/powercord`?

**Comment by ferpykins** [comment]
![image](https://user-images.githubusercontent.com/35282681/52743556-e6ccd580-2f9f-11e9-937e-eecfcaf9ab95.png)
This is what's there.

**Comment by aetheryx** [comment]
try cloning powercord in a folder other than System32

**Comment by ferpykins** [comment]
That did it! Thanks!
