### ISSUE TITLE
[Translator] Pings don't get translated back properly when reverting to original language

### ISSUE THREAD

**Issue by Nevvulo** [powercord-org/powercord#108]
**Describe the bug**
Translating pings *to* another language works alright, but translating from another language *back to* English (or the original language) produces raw HTML.

**To Reproduce**
* Convert any message containing a ping to another language
* Click "Translated from [language]".

**Expected behavior**
I expected the ping to convert back (somewhat) normally, at least displaying the text from the ping and not the raw HTML.

**Desktop (please complete the following information):**
 - OS: Windows 10 1809
 - Discord version: Release Channel: canary - Build Number: 32470

**Additional context**
Here is a screenshot of what the bug looks like in action. ![image](https://massive-legend.nevulo.xyz/7xV53lVe.png) This same behaviour also seems to apply for the "(edited)" tag ![image](https://massive-legend.nevulo.xyz/I2rjE2GN.png)

**Comment by cyyynthia** [comment]
Related to #45

**Comment by davidcralph** [comment]
Also applies to emoji as well (ignore the message, we're talking about cool nederlands muziek)

![image](https://user-images.githubusercontent.com/14052956/53520715-34802c80-3ace-11e9-8858-7ea783f5d23c.png)

**Comment by cyyynthia** [comment]
Yeah this will get fixed as well when we'll properly get/set message contents

**Comment by davidcralph** [comment]
fix it fast or ur fired

**Comment by cyyynthia** [comment]
i'm not hired

**Comment by davidcralph** [comment]
According to GitHub, you work at an organisation called Powercord

![image](https://user-images.githubusercontent.com/14052956/53521169-56c67a00-3acf-11e9-9799-a731ec9cb093.png)

**Comment by cyyynthia** [comment]
lies

![lies](https://i.bowser65.xyz/47f9eb2435.png)

**Comment by davidcralph** [comment]
right that's it i'm calling bill gates

**Comment by cyyynthia** [comment]
that's it i'm calling fbi
what's your address again?

**Comment by davidcralph** [comment]
North Yorkshire, England, United Kingdom

good luck finding me it's the biggest county in england and the fbi have no power here

**Comment by cyyynthia** [comment]
dw i'll let mark zuckerberg know as well

**Comment by davidcralph** [comment]
Shit, not him. His fucking company keeps giving me friend suggestions of people who go to my school but I have no friends so it's completely useless to me. I don't even have the fucking app on my phone..

**Comment by cyyynthia** [comment]
![dab](https://cdn.discordapp.com/emojis/549672986131693569.gif?v=1)
