### ISSUE TITLE
Right clicking a role and right clicking another one doesn't make the right-click menu dissappear

### ISSUE THREAD

**Issue by jtsshieh** [powercord-org/powercord#109]
**Describe the bug**
Right clicking a role to bring up its context menu and clicking on a different role keeps the context menu up.

**To Reproduce**
1. Right click on a role
2. Click on a new role
3. Watch as the context menu stays until you click out.

**Expected behavior**
When you right click a role and click on another one, the context menu should disappear.

**Desktop (please complete the following information):**
 - OS: Windows 10 1803
 - Discord version: "Release Channel: canary - Build Number: 32597"

**Additional context**

**Comment by aetheryx** [comment]
cannot reproduce, canary 32805. anyone else?

**Comment by cyyynthia** [comment]
![can repro](http://breaking-discord.is-my-k.ink/7be8306f61.gif)

**Comment by aetheryx** [comment]
nvm can repro as well, misunderstood bug
