### ISSUE TITLE
Hidden emotes still in autocomplete.

### ISSUE THREAD

**Issue by SacreBleuXCVII** [powercord-org/powercord#117]
**Describe the bug**
Hidden emotes are not properly hidden from the autocomplete, instead they are invisible.

**To Reproduce**
1) Hide the emotes for the Powercord server.
2) Type `:beta` and then press enter, it will autocomplete to `:betatester:` even if it doesn't show in the autocomplete and other emotes are being shown instead.

**Expected behavior**
It should not autocomplete to `:betatester:`, instead to the first emote shown in the autocomplete if there was one.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Discord version: Release Channel: canary - Build Number: 32982

**Comment by cyyynthia** [comment]
Fixed in #220
