### ISSUE TITLE
[Emote Utility] Cloning an animated emote to a guild fails even if animated emote slots are free

### ISSUE THREAD

**Issue by jacksonrakena** [powercord-org/powercord#119]
**Describe the bug**
This error is received if the selected guild when cloning emojis has no regular emoji slots remaining, but animated slots are free (when cloning animated emoji).
![image](https://user-images.githubusercontent.com/44521335/53669098-ca88a280-3cda-11e9-891d-7a79d155cb34.png)

**To Reproduce**
1) Right-click an **animated emoji**
2) Emoji -> Clone to
3) Select a guild that has **no regular slots left**, but has animated slots free.
4) Receive the above error.

**Expected behavior**
The animated emoji is cloned to the guild and occupies one of the animated emoji slots.

**Desktop:**
 - OS: Windows 10 
 - Discord version: Canary 33046

**Additional context:**
The emote in question was posted inside the guild I tried to clone it to. 
Guild in question has 50 regular emotes and 1 animated emotes.

**Comment by GreemDev** [comment]
Can't reproduce.
Same OS and Discord version as @thecatitude.

**Comment by jacksonrakena** [comment]
[thatsalotofthonk.zip](https://github.com/powercord-org/powercord/files/2921302/thatsalotofthonk.zip)
Same error on a fresh test guild with the attached 50 thonk copies filling all regular slots.

**Comment by cyyynthia** [comment]
Can't repro as well, seems like a dumb race condition.
According to what got said on Discord, it sounds like a plugin issue.

**Comment by jacksonrakena** [comment]
Can confirm #121 fixed the issue in the original + test guild on my end.
