### ISSUE TITLE
[Feature Request] Showing commit message on the update modal

### ISSUE THREAD

**Issue by SacreBleuXCVII** [powercord-org/powercord#120]
**Describe the feature request**
Showing the latest commit message on the update modal.

**What Plugin would it be for?**
Updater

**Expected behavior**
When the update modal asking if the user wants to update pops up, it should also show the latest commit message.

**Comment by cyyynthia** [comment]
Problem is that we can easily get 2/3 or sometimes 6 commit in the same update, or more if you don't open Discord for any reason. Related to #111

**Comment by SacreBleuXCVII** [comment]
For that you could maybe make it like `Latest commit message + X More Updates` if possible?

**Comment by cyyynthia** [comment]
hmm I'll look into it, with maybe an "Update Summary" modal for when there is more than 1 commit

**Comment by cyyynthia** [comment]
To group everything related to Updater updates, i made a global issue available here #230, so discussions/tracking will continue there
