### ISSUE TITLE
[Spotify Bug] Warning if the song is already in the playlist on adding

### ISSUE THREAD

**Issue by davidcralph** [powercord-org/powercord#124]
**Describe the feature request**
On Spotify, it warns you if the song you are adding to a playlist is already in the playlist. Maybe the add to playlist modal can get a popup for this as well?

![image](https://user-images.githubusercontent.com/14052956/53688806-7b298d00-3d41-11e9-9c48-d69533e9c5f0.png)

**What Plugin would it be for?**
Spotify

**Expected behavior**
Like Spotify

**Comment by Kanin** [comment]
It's been 8 months could we please get a fix for this 👀 it's a real pain and makes the feature nearly useless. Also this should be labeled as `Spotify Bug` imo. Though this may have been created before the issue template.

**Comment by davidcralph** [comment]
labelled as requested

**Comment by ghostlydilemma** [comment]
bowsu pls gib i need this

**Comment by Kanin** [comment]
Don't mind me, just bumping this for the sake of my playlists.. poor things, you should feel bad for them.. having the same song in them more than once :(

**Comment by cyyynthia** [comment]
Cyber gave a quick look and it looks kinda painful because there don't seem to be other solutions than caching playlist contents, or fetching the entire playlist to compare against

**Comment by davidcralph** [comment]
I think the latter sounds like the best option

**Comment by Kanin** [comment]
https://developer.spotify.com/documentation/web-api/reference/playlists/get-playlists-tracks/ Can't you use this to check for a specific track in a playlist?

**Comment by TheCyberRonin** [comment]
So you'll have to check that endpoint and paginate it until end (100 songs per call max), until the playlist is all gone through every time you add a song to a playlist? Even if you add 4 songs to the playlist one after another, that will have to happen 4 separate times. That's super inefficient.

**Comment by Kanin** [comment]
> Use multiple parentheses to drill down into nested objects, for example:
`fields=items(track(name,href,album(name,href)))`

Can you not simply use this parameter to check if the song is in the list?

**Comment by cyyynthia** [comment]
It might be possible this landed on latest v2-dev
![image](https://user-images.githubusercontent.com/9999055/83353119-932afa80-a350-11ea-9c8d-7cce9cca8dcf.png)
