### ISSUE TITLE
[Feature Request] [Minor] Add translation functionality to usernames and other non-chatbox elements

### ISSUE THREAD

**Issue by jacksonrakena** [powercord-org/powercord#126]
**Describe the feature request**
Add the translation menus to the context menus for non-chatbot elements like the profile modal.
High-quality, vector rendered, CAD mockup of a potential design:
![image](https://user-images.githubusercontent.com/44521335/53863178-58072200-404e-11e9-83d1-d8c061b82888.png)

**What Plugin would it be for?**
`pc-translate` Translation plugin

**Expected behavior**
The translation menu would appear on usernames, Spotify tracks, games, and other text blocks on non-chatbox elements, such as in the profile modal.

**Comment by davidcralph** [comment]
this mockup design is so high quality i want to hire you

**Comment by cyyynthia** [comment]
Translations features are no longer part of Powercord; Check out https://github.com/KyzaGitHub/message-translate and ask for new features there if you want some new ones.
