### ISSUE TITLE
[Feature Request] A plugin to display your local time to other users

### ISSUE THREAD

**Issue by cloudrac3r** [powercord-org/powercord#127]
When enabled, other users with the plugin would have the ability to see your local time by opening your user panel (e.g. by clicking your name in the guild member list, or right click > profile for the full profile popout).

This plugin would have a setting to disable broadcasting your local time to protect your privacy. This setting would be disabled by default.

This could be implemented by periodically broadcasting your time zone's UTC offset to the Powercord web server, and this offset would be fetched from that web server and decoded into a local time when somebody clicks your profile.

**Comment by davidcralph** [comment]
can we also get a plugin like this for birthday as well, maybe in the same one (think something similar is in betterdiscord but aint touching that shit)

**Comment by cyyynthia** [comment]
Plugin suggestions are now in a dedicated repo, check [this issue](https://github.com/powercord-community/suggestions/issues/3)
