### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by IamTails** [powercord-org/powercord#128]
a mark *everything* read button somewhere

**Comment by Kanin** [comment]
I second this

**Comment by cyyynthia** [comment]
Ok so I managed to bring that feature in Powercord. However, as it may generate a huge amount of requests if you have multiple unread guilds I made it wait 1.5s between each acknowledge, so Discord can't really identify if it's a mod/selfbot or not. So marking everything as read may take some time
