### ISSUE TITLE
[Codeblocks] Doesn't have the correct format in embeds

### ISSUE THREAD

**Issue by 21Joakim** [powercord-org/powercord#131]
**Describe the bug**
Codeblocks in embeds do not have the same format enhancements as it has when it's not inside an embed.

**To Reproduce**
Have a bot send a message containing an embed with a codebock inside of it.

**Expected behavior**
I expect the codeblock to have the same formatting inside an embed,

**Desktop**
OS: Windows
Discord version: Canary - Build Number: 33687

**Additional context**
![image](https://user-images.githubusercontent.com/11248267/54136775-a89ac880-441c-11e9-8c82-32833fc69cf5.png)

**Comment by GreemDev** [comment]
Noticed this as well.

**Comment by jacksonrakena** [comment]
Looks like this shitty BetterDiscord clone lets down the oppressed white gamer YET AGAIN. 

(/s. Can reproduce on Windows)
