### ISSUE TITLE
[Beta Tester Badge] Not Showing On Own Profile

### ISSUE THREAD

**Issue by L0stIllusion** [powercord-org/powercord#132]
**Describe the bug**
When given the Beta Tester role, it is expected to see a ``Powercord Beta Tester`` badge, which is true except when opening one's self profile. With Powercord installed, and role applied in the Powercord Discord server, there is no badge to be seen.
**To Reproduce**
1) Make Discord Account
2) Install Powercord
3) Join Powercord Discord server
4) Get Beta Tester Role
5) Click on yourself and view your profile.
6) No ``Powercord Beta Tester`` badge is added!

**Expected behavior**
When executing the above steps, instead of no ``Powercord Beta Tester`` badge being added and visible in step 6, one would expect to see a ``Powercord Beta Tester`` in their profile like everyone else's.
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Discord version: Release Channel: canary - Build Number: 33717

**Additional context**
It really ruins my ego, not being able to see this badge I proudly own.

**Comment by aetheryx** [comment]
NAB.

Badges aren't based off of roles in the server - they have to be manually added on the web dashboard. You seem to be dealing with a case of a developer who was too lazy to open a browser. I would suggest pinging this developer and asking them to give you your righteous badge that you proudly own.
