### ISSUE TITLE
Server icon disappears once joining a new server

### ISSUE THREAD

**Issue by Nexus237** [powercord-org/powercord#133]
**Describe the bug**
Does not display the icon of the new server once joined using the invite.

**To Reproduce**
1. Join a new server
2. Scroll down the server list a bit and scroll back up

**Expected behavior**
The new server icon does not disappear

**Desktop (please complete the following information):**
 - OS: Windows 
 - Discord version: Canary - 33717

**Additional context**
https://i.imgur.com/Zy23fkk.gifv (streamer mode is enabled but that does not make any difference)

**Comment by cloudrac3r** [comment]
I also have this issue. Reloading the client (Ctrl-R) does not fix it: sometimes the server icons don't appear at all, sometimes they appear briefly but disappear as soon as I begin to scroll the server list.

**Comment by cloudrac3r** [comment]
This is a bug in the Guild Folders plugin. Its setting file (settings/pc-guilds.json) stores a list of all servers, but this list doesn't get updated with new entries when a new server is joined.

You can make your new servers show up by deleting the entire key `guilds` from the settings file and reloading the client. The key will be rewritten whenever you drag and drop a server in the list.

**Comment by cyyynthia** [comment]
In the meantime, you can disable the plugin in your settings (User settings
> Plugins). I'll fix that when I get home, around 6pm (baguette land time)
