### ISSUE TITLE
Server order doesn't update

### ISSUE THREAD

**Issue by SacreBleuXCVII** [powercord-org/powercord#136]
**Describe the bug**
Changing the server order on another device won't update it on the client with Powercord installed.

**To Reproduce**
Change the server order on another device.

**Expected behavior**
The client that has Powercord installed should also update the order.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Discord version: Release Channel: canary - Build Number: 33959

**Comment by GriefMoDz** [comment]
Cannot seem to reproduce this bug report as the following steps don't result in such behavior (at least for me). As an example of another device, I used an iPhone 7 running iOS 12.1 and installed with Discord's mobile app - `Testflight - Vesion 2.5.2 (Build 13014)`.

OS: `Windows 10 Home - Version 1803 (Build 1734.648)`
Discord version: `Canary - Build Number: 34858 - Powercord's git revision: 10b10c8bbb11ffab1a26f434f440d0a6d5519c66@v2`

**Comment by cyyynthia** [comment]
A temporarily fix got implemented in f3b68b820f089f16ef6a212ddd6987280d4036fa. I'll try to not break it again once I'll re-enable the local store for guild order in folders
