### ISSUE TITLE
Certain settings menu options are empty (MacOS)

### ISSUE THREAD

**Issue by twnlink** [powercord-org/powercord#137]
**Describe the bug**
When clicking on the "General Settings" or "Plugins" tab the entire Window goes Discord grey with a few errors in the console.

**To Reproduce**
1. Open Discord
2. Open Settings
3. Click on either General Settings or Plugins  
**Expected behavior**
I expected the plugins menu to open.
  
 - OS: MacOS
 - Discord version: Release Channel: stable - Build Number: 33990

**Additional context**
The console errors I get:
![errors](https://i-am.a-virg.in/z4fosbRp)
![other errors](https://i-am.a-virg.in/bPoN3PHf)

**Comment by aetheryx** [comment]
not actually a crash, rather just effectively an empty settings tab. hit escape to exit out of it. doing so will also fix the issue until next reboot

**Comment by twnlink** [comment]
ah alright, should this be closed?

**Comment by aetheryx** [comment]
nope! still definitely a bug, high-priority at that (we've been aware of it and a fix is being worked on). just edit the title and body to be accurate.
