### ISSUE TITLE
[Feature Request] Reply button

### ISSUE THREAD

**Issue by ghost** [powercord-org/powercord#138]
**Describe the feature request**
A plugin that adds a "Reply" button next to a user in the chat.

**What Plugin would it be for?**
Could be called "Reply button

**Expected behavior**
When clicked, it will automatically add the mention into the text area in the chat. It should use userID for better tagging/mentioning.
Bonus: Another quote button next to it which includes a quote of the message. (uses codeblocks)

**Comment by cyyynthia** [comment]
For quick mentionning people we can consider shift+click a viable-enough solution, and for quoting [that plugin](https://github.com/NurMarvin/quote) is now out and allows quoting. Feel free to re-open if that doesn't solve the issue completely!
