### ISSUE TITLE
Broken Images on User Profile

### ISSUE THREAD

**Issue by zspri** [powercord-org/powercord#145]
**Describe the bug**
Several broken images are inserted into a user profile card.
Screenshot: https://i.imgur.com/dyDEne6.png
<details>
<summary>Element tree</summary>
<code>
#app-mount > div:nth-child(5) > div.modal-1UGdnR.pc-modal > div.inner-1JeGVc.pc-inner > div > div.topSectionNormal-2-vo2m.pc-topSectionNormal > header > div.headerInfo-30uryT.pc-headerInfo > div.flex-1xMQg5.flex-1O1GKY.pc-flex.pc-flex.horizontal-1ae9ci.horizontal-2EEEnY.flex-1O1GKY.directionRow-3v3tfG.justifyStart-2NDFzi.alignStretch-DpGPf3.noWrap-3jynv6.profileBadges-2vWUYb.pc-profileBadges > div.powercord-badge.\30
</code>
</details>

**To Reproduce**
1. Right-click a user's message
2. Click "Profile"

**Expected behavior**
These images do not appear on the profile.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home, Version 1903, Build 18356.16
 - Discord version: Release Channel: canary - Build Number: 34340

**Additional context**
N/A

**Comment by aetheryx** [comment]
update to latest master - please close this issue if you've updated and the issue is resolved

**Comment by cyyynthia** [comment]
Looks like you're not up to date. Try updating and see if it still breaks

**Comment by zspri** [comment]
Looks fixed in 34384.
