### ISSUE TITLE
[Feature Request] Plugin for Discord Call Remix

### ISSUE THREAD

**Issue by L0stIllusion** [powercord-org/powercord#163]
**Describe the feature request**
There's a 0.1% chance of when someone calls you a [remixed version of the default song is used](https://www.youtube.com/watch?v=dwexm0erwn8). With this plugin enabled, whenever you get a call, it should play the aforementioned song instead of the default.
**What Plugin would it be for?**
Discord Ringtone Remix
**Expected behavior**
With this plugin enabled, whenever you get a call, it should play the aforementioned song instead of the default.

**Comment by brandon9707** [comment]
If this get accepted, here's a link to the "Incoming Call Beat": https://discordapp.com/assets/b9411af07f154a6fef543e7e442e4da9.mp3

**Comment by cyyynthia** [comment]
Plugin suggestions are now in a dedicated repo, check [this issue](https://github.com/powercord-community/suggestions/issues/2)
