### ISSUE TITLE
Emote Utility Hidden Guilds Error

### ISSUE THREAD

**Issue by SacreBleuXCVII** [powercord-org/powercord#174]
**Describe the bug**
Hiding guilds via the Emote Utility plugin doesn't hide them in the emoji picker and causes an error to occur.

**To Reproduce**
* Hide some guilds.
* Open the emoji picker.

**Expected behavior**
For the emojis from the hidden guilds to be hidden.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Discord and Powercord version: Release Channel: canary - Discord's Build Number: 36215 - Powercord's git revision: 6cc32198e661dd1e5ea82fda9d40cdcd5640b36a@v2

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme
 
```
[Powercord:Injector] Failed to run injection "pc-emojiUtility-hideEmojisPickerRm" TypeError: this.getGuild is not a function
    at /Users/X/Downloads/Discord/powercord/src/Powercord/plugins/pc-emojiUtility/index.js:538
```

**Comment by cyyynthia** [comment]
Fixed in d5bbf42e22c4819d04ab492d9c28ea730e9253fc
