### ISSUE TITLE
[Feature Request] Auto Plugin Updater

### ISSUE THREAD

**Issue by jtsshieh** [powercord-org/powercord#186]
**Describe the feature request**
Somewhere part of the plugin manager to update all the third-party plugins from.

**What Plugin would it be for?**
pc-pluginManager

**Expected behavior**
1. Click on a button to either update one or update all your plugins
2. `git pull` the source to update and reload
3. send notifications when a plugin update is ready

**Comment by cyyynthia** [comment]
This is a planned feature that will come with many other updater improvments

**Comment by jtsshieh** [comment]
Should I leave the issue open, or should I close it?

**Comment by cyyynthia** [comment]
leave it open, we'll close it once it becomes a thing 😄

**Comment by cloudrac3r** [comment]
[:zoomeyes:](https://github.com/cloudrac3r/pc-cadence-pluginUpdater)

**Comment by cyyynthia** [comment]
To group everything related to Updater updates, i made a global issue available here #230, so discussions/tracking will continue there
