### ISSUE TITLE
[Feature Request] Ping on keywords

### ISSUE THREAD

**Issue by figgyc** [powercord-org/powercord#190]
**Describe the feature request**
For each server have a list of words then get pinged when it gets said

**What Plugin would it be for?**
New plugin i guess

**Expected behavior**
Somewhere there is a list of keywords and you can type a word. then when someone says it you get pinged just like if you were mentioned

**Comment by cyyynthia** [comment]
Plugin suggestions are now in a dedicated repo, check [this issue](https://github.com/powercord-community/suggestions/issues/1)
