### ISSUE TITLE
[Bug] Settings are broken

### ISSUE THREAD

**Issue by MrLar** [powercord-org/powercord#193]
**Describe the bug**
All kinds of settings are no longer working/saving

**To Reproduce**
Try to change any setting (binary are most apparent)

**Expected behavior**
It to work lol

**Desktop (please complete the following information):**
 - OS: I don't think this matters
 - Discord and Powercord version: Release Channel: canary - Discord's Build Number: 38674 - Powercord's git revision: ae07fea9e70faca4be1be1c471db86f73994e578@v2

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme

**Comment by Kanin** [comment]
This makes Kanin a big saddo
