### ISSUE TITLE
[Feature Request] Soundcloud support

### ISSUE THREAD

**Issue by thetakodev** [powercord-org/powercord#197]
**Describe the feature request**
A spotify like player but for soundcloud

**What Plugin would it be for?**
Name of plugin if applicable

**Expected behavior**
A music player integartion just like the spotify player but for soundcloud

**Comment by cyyynthia** [comment]
SoundCloud doesn't provide an API, and even if we manage to get access to it it won't provide everything we need

**Comment by davidcralph** [comment]
They actually do provide an API (https://developers.soundcloud.com), but sadly no one can currently sign up to it.

**Comment by cyyynthia** [comment]
registrations are closed for literally years, at this point you can just say they don't ¯\\\_(ツ)_/¯

**Comment by davidcralph** [comment]
lmao yes it do be like that

**Comment by TheCyberRonin** [comment]
I have API access from a few years ago still 👀

**Comment by cloudrac3r** [comment]
ZOOMEYES

**Comment by davidcralph** [comment]
EYESHAKE

**Comment by thetakodev** [comment]
@Bowser65 I would suggest to look at the tokens which are used in these 2 repositories
https://github.com/Miserlou/SoundScrape/blob/master/soundscrape/soundscrape.py
https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/soundcloud.py
