### ISSUE TITLE
Guild folders does not support animated icons

### ISSUE THREAD

**Issue by cloudrac3r** [powercord-org/powercord#198]
**Describe the bug**
Guild """folders""" plugin does not support animated guild icons.

**To Reproduce**
Hover the icon of a server that has an animated icon set up. Animated icons are available at boost tier 1, which costs 2 boosts. The icon should animate, but does not.

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme
 
You can get animated icons to display by disabling the guild """folders""" plugin.

**Comment by cyyynthia** [comment]
wdym this is a great feature that decancers your discord client mmlol

**Comment by MasicoreLord** [comment]
Hope that issue is fixed.
