### ISSUE TITLE
Emoji Utility does not respect extra slots from Nitro boosting

### ISSUE THREAD

**Issue by NurMarvin** [powercord-org/powercord#199]
**Describe the bug**
When trying to clone an emoji to a server that has all the default emoji slots used, but has extra slots granted from Nitro boosting, the emoji utility won't let you clone the emoji.
Same goes for creating a new emoji from the context menu on an image.

**To Reproduce**
1. Have a server with at least nitro boosting tier 1
2. Fill the emoji slots to the normal limit (50)
3. Try cloning or creating an emoji using the emoji utitlity

**Expected behavior**
The Emoji Utility should consider the extra slots and only produce an error if the extra slots are in use as well.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Discord and Powercord version: "Release Channel: canary - Discord's Build Number: 39084 - Powercord's git revision: fa17c43323de66ccb60162b40ad8097a5f093505@v2"

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme

**Comment by cloudrac3r** [comment]
Haven't tested but should be as simple as changing this function to this:

	EmojiUtility.getMaxEmojiSlots(guildId) {
		return (this.getGuild(guildId).premiumTier || 0)*50 + 50;
	}

Maybe?
