### ISSUE TITLE
[Feature Request] Merge advanced-title-bar with titlebarGames

### ISSUE THREAD

**Issue by davidcralph** [powercord-org/powercord#200]
**Describe the feature request**
This would require Lars' approval, but something that would be cool would be if we got the two plugins merged into one with options to enable/disable the features of advanced-title-bar. Just makes sense to be honest since then you would only need to install one plugin instead of two to get a "complete" titlebar enhancement experience (could have a possible performance increase as well??). This also makes it useful as it would be easier to update the plugin (on both developer and end-user side) when Discord breaks things, new features are added, or if you need to reinstall Powercord on another system for whatever reason.

**What plugins would it be for?**
titlebarGames and advanced-title-bar

**Expected behaviour**
A simple merge of the two plugins to provide more features in one.

**Comment by cyyynthia** [comment]
@MrLar

**Comment by MrLar** [comment]
I mean I wouldn't mind, as I personally didn't really have plans to maintain it much more anyway, given I moved to Linux.

**Comment by cyyynthia** [comment]
Can we still consider this as pertinent? As we said a couple times Powercord will when it gets out of beta we'll probably drop most non-core plugins from the pre-installed plugin list, plus the fact that advanced-title-bar is as far as i know unmaintained

**Comment by davidcralph** [comment]
I think we can consider this as pertinent but it'd be better to move the pluginto powercord-community; advanced-title-bar is unmaintained based off what Lars said above but it should still work properly.

**Comment by davidcralph** [comment]
Since Discord has canned the game store/library-related stuff, I expect all the features related to it to disappear in future updates. As such, I am closing this PR.
