### ISSUE TITLE
Fullscreening YouTube embeds causes Discord to fullscreen.

### ISSUE THREAD

**Issue by ghost** [powercord-org/powercord#201]
**Describe the bug**
After unfullscreening a video from an embed from YouTube, Discord is considered a fullscreen application until restart.

**To Reproduce**
Open an embed in fullscreen from YouTube.
Unfullscreen the embed.

**Expected behavior**
Discord would go back to windowed mode after unfullscreening the embed.

**Desktop**
 - OS: Windows
 - Discord and Powercord version: Release Channel: canary - Discord's Build Number: 39214 - Powercord's git revision: b7c00c493d80fe26c93a20bc96d7728f6752a298@v2

**Additional context**
 - [V] I checked if Discord and/or Powercord are up to date
 - [V] I made sure this is not related to an external plugin or a theme

**Comment by cyyynthia** [comment]
This is not a bug related to Powercord, it happens on vanilla Discord as well (Tried just now). What you can do to exit fullscreen is using `Ctrl+Shift+F`. This seems to be related to Electron v6 beta which is only used by canary client
