### ISSUE TITLE
Injector not working

### ISSUE THREAD

**Issue by Cool-ShowTTV** [powercord-org/powercord#205]
**Describe the bug**
When ever I try to inject it makes discord not open

**To Reproduce**
clone
npm i
npm run plug

**Expected behavior**
Inject with out crashing

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Discord and Powercord version: Discord app-0.0.242 and the powercord is the latest release 

**Additional context**
 - [X] I checked if Discord and/or Powercord are up to date
 - [X] I made sure this is not related to an external plugin or a theme
 
![image](https://user-images.githubusercontent.com/22648256/59469450-d66c2080-8e02-11e9-9342-d2b912435561.png)

**Comment by aetheryx** [comment]
you seem to have cloned powercord in a subdirectory of an existing git repository - try cloning it in an empty folder instead, or somewhere like your desktop

**Comment by Cool-ShowTTV** [comment]
Thank you it works now.
