### ISSUE TITLE
[Feature Request] penis.js support

### ISSUE THREAD

**Issue by cloudrac3r** [powercord-org/powercord#211]
Please add support for [penis.js](https://github.com/edankwan/penis.js) so that I can use the awesome expression B==D (or B===D if I'm feeling spicy) to compare values in my plugins.

**Comment by cyyynthia** [comment]
I'm sorry, but for you i'd imply you'll have to use `BD` which is an obvious reference to BetterDiscord. We therefore can't add support for it.

Sincerely,
Bowser65,
​ ​ ​ ​ Founder & CEO @ Borkenware S.à r.l
​ ​ ​ ​ Software Engineer @ Aethcord LLC
​ ​ ​ ​ Engineer @ Union Chat LLC
