### ISSUE TITLE
[Feature Request] CaSe SeNsItIvE commands

### ISSUE THREAD

**Issue by LandenStephenss** [powercord-org/powercord#225]
**Describe the feature request**
As the current command system stands. You have to run prefix**help** exactly, for example you cannot do prefix**HELP**. I would like to have that changed, I already have a fix for it (see code below)
Line 11 src > plugins > pc-commands > monkeyPatchMessages.js
```js
   const [ cmd, ...args ] = message.content.slice(powercord.api.commands.prefix.length).toLowerCase().split(' ');
```

**What Plugin would it be for?**
pc-commands

**Expected behavior**
Instead of having to use all lowercase letters to run a command, You could use all uppercase (this also helps in the event of someone sending prefix**help** to a random channel with no context and looking like an idiot

**Comment by intrnl** [comment]
Would've been wise to only make the command lowercase and not the arguments too, I think

**Comment by LandenStephenss** [comment]
Good point.
Updated code, Line 12, same file
```js
    const command = powercord.api.commands.commands.find(c => [ c.command, ...c.aliases ].includes(cmd.toLowerCase()));
```
Although i did notice on the help command it is case sensitive too
