### ISSUE TITLE
[Feature Request] Cute Badge (for emma)

### ISSUE THREAD

**Issue by NurMarvin** [powercord-org/powercord#241]
**Describe the feature request**
A badge for cute people (or just emma/@GhostlyDilemma).
Would suggest using the same badge as Cutecord:
<img src="https://canary.discordapp.com/assets/62dc78f6f9a73954e6454da485ea8147.svg" width=64 height=64></img>

**What Plugin would it be for?**
pc-badges

**Expected behavior**
A `Cute` Badge showing up in the profile of cute people (or just emma/@GhostlyDilemma).

**Comment by cloudrac3r** [comment]
am i cute

**Comment by NurMarvin** [comment]
yes, very

**Comment by cyyynthia** [comment]
This feature is called custom badges and already exists smh
