### ISSUE TITLE
Codeblocks broken again after newest version - my findings

### ISSUE THREAD

**Issue by ghostlydilemma** [powercord-org/powercord#242]
**Describe the bug**
Codeblocks are not being rendered correctly.

**To Reproduce**
Enabled the pc-codeblocks plugin in any appearance setting and open a channel with codeblock-messages.

**Expected behavior**
Inject the changes correctly to make codeblocks look nicer.

**Desktop (please complete the following information):**
 - OS: Arch
 - Discord and Powercord version: 
Release Channel: canary
Discord's Build Number: 47471
Powercord's git revision: 95603c405f19b1743be1e18c24658df58215da57@v2

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [ ] I made sure this is not related to an external plugin or a theme
^ well it is a plugin...
 
My findings from digging through the internals a little - what is broke and maybe how to fix it
* Selector for getting the message - fixable by changing the `messageClasses` and `messageQuery` variables:
```JS
const messageClasses = await getModule([ 'contentCompact', 'contentCozy' ]);
const messageQuery = `.${messageClasses.content.replace(/ /g, '.')} > div:last-child`;
```
* The Try Catch block for determining whether or not a message contains a codeblock fails completely now to the fact that `contentParsed` is not part of the `message` object anymore. There seems to be a new variable called `customRenderedContent` which currently only outputs `undefined`. (Maybe this is only for special channel types? / Maybe just bugged until next update). Content itself just outputs the raw message content as seen in the screenshot below:

![here](https://media.discordapp.net/attachments/539444133568446475/634177700843487234/unknown.png)

* The lower check before actually injecting the codeblock checks for ref, which seems to be gone as well:
```JS
if (
    hasCodeblock &&
    this.ref instanceof Element
)
```
`ref` seems to be replaced with `refs` which is just an empty object:
![image](https://user-images.githubusercontent.com/29519722/66968936-a15d2c80-f087-11e9-9c1f-3d53ae8cf51d.png)

It still works as expected on first application/plugin load, but fails afterwards due to the reasons mentioned above. For a more detailed analysis of what I found: [Powercord Server](https://canary.discordapp.com/channels/538759280057122817/539444133568446475/634177415744323610)

**Comment by NurMarvin** [comment]
Code blocks in embeds are still broken:
![DiscordCanary_2019-10-17_22-29-23](https://user-images.githubusercontent.com/17235016/67044927-965cd780-f12d-11e9-9fb9-d93e1b061b18.png)

Please re-open this issue till this is fixed as well.

**Comment by GriefMoDz** [comment]
> 
> 
> Code blocks in embeds are still broken:
> ![DiscordCanary_2019-10-17_22-29-23](https://user-images.githubusercontent.com/17235016/67044927-965cd780-f12d-11e9-9fb9-d93e1b061b18.png)
> 
> Please re-open this issue till this is fixed as well.

https://github.com/powercord-org/powercord/commit/5bcd29e3d0dc40faf2903a859561e865ca037951 should (hopefully) mark this as resolved. Let me know if it has been, otherwise I'll leave this issue opened. :smiley:

**Comment by NurMarvin** [comment]
Updated to latest version and still seems to be broken.

**Comment by cyyynthia** [comment]
Can't repro, `Release Channel: canary - Discord's Build Number: 47580 - Powercord's git revision: c98b8cc1ce611a8b3d1ad18364b8864d1bc65c50@v2`
![e](https://i.bowser65.xyz/cb039fe909.png)

**Comment by cyyynthia** [comment]
Finally able to repro, yes

It only affets codeblocks that are in a field value. Here is a working repro case (Powercord server): https://canary.discordapp.com/channels/538759280057122817/554406787764191294/634812209008082963

**Comment by GriefMoDz** [comment]
Closing and marking this issue as resolved as fixes https://github.com/powercord-org/powercord/commit/3525e82ec395e6e998abf37bc554985c0ce9a4c7 this.
