### ISSUE TITLE
Context menus do overflow

### ISSUE THREAD

**Issue by cyyynthia** [powercord-org/powercord#243]
**Describe the bug**
they overflow
![](https://uwu.learndesk.app/c5752564da.png)

**To Reproduce**
right click

**Expected behavior**
they shouldn't

**Desktop (please complete the following information):**
 - OS: (irrelevant)
 - Discord and Powercord version: latest smh

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme
 
btw have i told you i use arch

**Comment by davidcralph** [comment]
ur not using arch that screenshot is very clearly windows TEN you absolute fake arch user you are a disgrace to the entire arch community and you should be ashamed of claiming that you are an arch user when you have this blatantly obvious not arch screenshot in the same message

absolutely disgusted

**Comment by cyyynthia** [comment]
https://canary.discordapp.com/channels/538759280057122817/538759280497786890/625252360456765451

**Comment by davidcralph** [comment]
nice celery processor

**Comment by cyyynthia** [comment]
yeah now YOU, disgrace to the entire arch community, go buy a macbook that's all you deserve

**Comment by davidcralph** [comment]
i would SIR but argos won't add the macbook to my trolley 😠

**Comment by ghostlydilemma** [comment]
no arguing uwu
let's all just use what we like thank u

**Comment by davidcralph** [comment]
i agree

**Comment by Kanin** [comment]
no u

**Comment by GriefMoDz** [comment]
https://github.com/powercord-org/powercord/commit/3525e82ec395e6e998abf37bc554985c0ce9a4c7 partially fixes the overflowing of context menus although it doesn't take care of everything just yet - sub context menus still go off-screen. For this reason I'll be keeping this opened as the issue remains somewhat standing.
