### ISSUE TITLE
[Feature Request] Make pc-updater update node_modules aswell

### ISSUE THREAD

**Issue by LandenStephenss** [powercord-org/powercord#248]
**Describe the feature request**
Whenever using pc-updater to update all of your plugins it should also update npm_modules since the developer has most likely updated to that version as well.

**What Plugin would it be for?**
pc-updater

**Expected behavior**
When updating plugins it will update all of the out-of-date node_modules, could be useful, could not. Up to you guys.

**Comment by cyyynthia** [comment]
Powercord's node_modules does get updated when there is a powercord update.
If you're speaking about plugins themselves, they can't have their package.json with modules, so I don't get what you're reffering to. Can you enlighten me?

**Comment by LandenStephenss** [comment]
Didn't realize node_modules gets updated. May bad. Will close
