### ISSUE TITLE
[Spotify] Resume button doesn't work.

### ISSUE THREAD

**Issue by funlennysub** [powercord-org/powercord#250]
**Describe the bug**
When you pause the song from Spotify app and wait 20 minutes, but when you tries to resume it from Discord, song wouldn't be resume.

**To Reproduce**
Pause song from Spotify app and wait for 20 mins and try to resume it from Discord

**Expected behavior**
Song should resume.

**Desktop:**
 - OS: Windows 10 Pro 1903
 - Release Channel: canary - Discord's Build Number: 48112

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme

**Comment by cyyynthia** [comment]
I did some tests recently, and sadly it looks like to be a bug on Spotify's end. The API we query (Connect Web API) is afaik still in beta and bugs can occur :(

What looks like to be happening is that Spotify stops considering your computer as an active device, which makes querying the API return an error "No active device". I'll see if we can't find a workaround, like keep in memory the last device you played on in memory and if that happens tell the API to set this device's state to active player.
