### ISSUE TITLE
[Feature Request] Clyde -> Powercord

### ISSUE THREAD

**Issue by Kanin** [powercord-org/powercord#260]
**Describe the feature request**
All plugin messages that are the default Clyde would be changed. The name would be changed to `Powercord` and the avatar would be ![image](https://cdn.discordapp.com/attachments/538759280497786890/555071986527633429/this-is-a-file.png)

(Possibly with the ability to customize the name/avi)

**What Plugin would it be for?**
Yes

**Expected behavior**
Kill Clyde and replace him with Powercord 👍

**Comment by Kanin** [comment]
Priority: Higher than Cheech and Chong
Reason: Make Kanin happy and make Powercord pretty uwu

**Comment by NurMarvin** [comment]
No

**Comment by Kanin** [comment]
> 
> 
> No

Heck off your opinion doesn't matter

**Comment by NurMarvin** [comment]
Make it an external plugin, I want to keep my Clyde.

**Comment by davidcralph** [comment]
@NurMarvin speaking fax here
