### ISSUE TITLE
[Feature Request] Update History

### ISSUE THREAD

**Issue by ghost** [powercord-org/powercord#261]
**Describe the feature request**
Logging what has been updated previously.
I sometimes plugins update, yes. But with the toast you don't know what you are updating most of the time. So often you're just updating without knowing what plugin has been fixed or not. Unless last updated becomes a thing in the plugins tab this would be quite useful.

**What Plugin would it be for?**
pc-updater

**Expected behavior**
You get an extra drop down with an `Update History` and it logs the updates from the past 5 restarts or the past 30 days. It should mention the commits and the date / time. A clickable link would be cool too.

**Comment by cyyynthia** [comment]
Before updating you can still give a look to the updater, as it shows all pending updates, like this:
![https://owo.learndesk.app/4fd3e0266c.png](https://i.serux.pro/4fd3e0266c.png)

I'm unsure if we really want to store previous update logs, not like it'd be hard or anything but if people want it we can make this a thing I guess

**Comment by cyyynthia** [comment]
This probably won't be worked on as it'd require persisting updates data which would be more work for nothing really useful. If you want to know what's been updated go to the updater before updating.

If some people think this is very useful, then feel free to comment on this. I am open to feedback as always but I don't feel like this feature is worth the time.
