### ISSUE TITLE
[Feature Request] Right-click embeds

### ISSUE THREAD

**Issue by Benricheson101** [powercord-org/powercord#263]
**Describe the feature request**
In Discord, you aren't able to right-click an embed to open the context menu with the delete button, pin button, etc.

**What Plugin would it be for?**
n/a
**Expected behavior**
Right-clicking inside or beside an embed would open the context menu so you don't have to click the 3 dots button.

**Comment by cyyynthia** [comment]
To request new plugins, please refer to the community organization instead. This is the place to request new plugins: https://github.com/powercord-community/suggestions

**Comment by Benricheson101** [comment]
I was thinking since it was such a small thing it could go here, but I guess that would be a better place. I’ll post it there.
