### ISSUE TITLE
[Feature Request] Autoload plugins and themes

### ISSUE THREAD

**Issue by CyberL1** [powercord-org/powercord#265]
**Describe the feature request**
Autoload plugins and themes

**Expected behavior**
Fetches plugins and themes automatically without restart

**Comment by lanye74** [comment]
It works for themes, at least; unsure about plugins

**Comment by cyyynthia** [comment]
You can go to your settings and request Powercord to fetch newly-added plugins and themes. I don't know if this is enough but given our plans of adding a Plugin Store which will already handle this I think the button is enough. Opinions?

**Comment by cyyynthia** [comment]
Closing due to the lack of input for over a year. We will not be watching the filesystem all the time to load plugins as soon as they appear; the button in settings is enough.
