### ISSUE TITLE
Cache built scss/less/stylus files

### ISSUE THREAD

**Issue by cyyynthia** [powercord-org/powercord#266]
Since Powercord now caches JSX files to improve speed, it might be a good idea to do the same with stylesheets that requires being passed through a preprocessor.

**Comment by intrnl** [comment]
Requires hashing all of its dependencies (imports) would it?

**Comment by cyyynthia** [comment]
I've made some progress regarding this (SCSS only) and the results are very promising. This is a technically production-ready thing, scss is built, cached and cache invalidation takes into account nested files.

 - imports resolve: Crawling SCSS files recursively to find out which files they do import (re-used later on during rendering)
 - cache key computation: Computation of the key used for caching. Includes reading files and hashing them through SHA1
 - render: Passing the SCSS through the render engine to transform it in pure CSS
 - compile: Total time took (sum of all the above + non-tracked ops)

![image](https://user-images.githubusercontent.com/9999055/82761302-f91bfd00-9df9-11ea-9a0c-1d773b33a00e.png)

**Comment by cyyynthia** [comment]
Landed with #330
