### ISSUE TITLE
[Feature Request] Message Send Event.

### ISSUE THREAD

**Issue by CatboyCoding** [powercord-org/powercord#267]
**Describe the feature request**
A feature similar to registering a command but it doesn't require prefixes (basically like BD i guess)

**What Plugin would it be for?**
A text modifier plugin I'm working on currently.

**Expected behavior**
Call an event in the plugin and replace content with the returned value.
(example:

    class MessageEventExample extends Plugin {
        onSendMessage(content) {
            return content.match(/\#\#.*?\#\#/) ? "ok boomer, " + content : content
        }
    }
(not tested))

**Comment by cyyynthia** [comment]
This is already doable by patching the `sendMessage` method, using pre-injections (injections that run before Discord's function; only accepts args, returns either the args (altered or not) or false to stop execution; declared by adding `true` as the last parameter of your inject). Module is pre-exported as `require('powercord/webpack').messages`.
