### ISSUE TITLE
[Spotify] Auto-pause prevention is not working.

### ISSUE THREAD

**Issue by vekett** [powercord-org/powercord#272]
**Describe the bug**
Despite having the 'No auto pause' setting activated, spotify still autopauses after 30 seconds of microphone use.

**To Reproduce**
Steps to reproduce the behaviour: Have voice activated for over 30 seconds with 'No auto pause' enabled.

**Expected behavior**
The Spotify playback should not pause.

**Desktop (please complete the following information):**
 - OS: GNU/Linux Debian 4.19.67-2
 - Discord and Powercord version: "Release Channel: canary - Discord's Build Number: 52006 - Powercord's git revision: 8418cdbd6abb7b54f8a165bce5ada9875621844a@v2"

**Additional context**
 - [ X ] I checked if Discord and/or Powercord are up to date
 - [ X ] I made sure this is not related to an external plugin or a theme

**Comment by GriefMoDz** [comment]
Thanks for taking the time to report this! A fix has landed in https://github.com/powercord-org/powercord/commit/69d2b34aec74520fd8c1c20f188fb94b4d5fe9e3 of the development branch (`"v2-dev"`).

Furthermore, as this is classed a "low priority" level bug, this commit will **not** be merged to stable (`"v2"`) until a later stage as we patiently wait for newly proposed features to become available.

If you're interested in testing this out for yourself, you can easily switch to the development branch by opening your "User Settings", navigating to the "Updater" tab, and selecting "Switch to development".

Now closing and marking this issue as resolved.
