### ISSUE TITLE
[Feature Request] Fake GitHub connection.

### ISSUE THREAD

**Issue by twnlink** [powercord-org/powercord#274]
**Describe the feature request**
A fake connection (that displays for Powercord users only) that allows you to show your GitHub page on your profile.

**What Plugin would it be for?**
I'd say Badges but maybe separating it into it's own plugin would be for the best.

**Expected behavior**
The plugin uses your Powercord account with a linked GitHub account to display your GitHub profile on your Discord profile as a fake connection. This is entirely optional of course, for privacy reasons.

**Comment by GriefMoDz** [comment]
Partially landed in c9f8adcc055f56f72b202ad4d35b8157a9915ffe - still need to work on the "optional" side of things, however most of the functionality such as displaying linked GitHub accounts under user modals is available to be tested on `v2-dev`. Thanks for the feature request!

**Comment by GriefMoDz** [comment]
As a follow up to my last comment, you can now find the proper finalized implementation of this feature request under https://github.com/powercord-org/powercord/commit/0d79ca80020390bb33fe50695a769c7b07c76697. I'll be marking this issue as closed. If you have any questions or concerns, please feel free to send me a message @ `M|-|4r13y ツ#1051`. Thanks!
