### ISSUE TITLE
Linking not working

### ISSUE THREAD

**Issue by resucutie** [powercord-org/powercord#275]
# Describe the bug
Linking isnt working. Okay, the part if oauth2 and the other stuff is working, but the integration with the client and the other stuff isnt working

# To Reproduce
1- Simply link the account. If not worked, try different languages in different regions. I use portuguese language with the brazil region

# Expected behavior
For some reason, when I try to link the account, nothing happens. It opens the oauth2 link, it authorize successfully, but the pc client says that it expirated.

# Desktop (please complete the following information):
 - OS: Linux (Linux mint 19.3, Linux 5.0.3.2-generic (i think)
 - Discord and Powercord version: Latest versions (Powercord dev branch)

# Additional context
 - [x] I checked if Discord and/or Powercord are up to date

 - [x] I made sure this is not related to an external plugin or a theme
 
# Add any other context about the problem here.

My english is bad, sry

**Comment by cyyynthia** [comment]
Are you talking about linking your Powercord Account to Discord? If yes, I can't reproduce.
[video](https://epic.weeb.services/%E2%80%8C%E2%80%8C%E2%80%8D%E2%80%8C%E2%81%A0%E1%A0%8E%E2%80%8C%E2%80%8B)

**Comment by SynergyBest** [comment]
The same thing happens to me
