### ISSUE TITLE
Powercord makes latest discord canary doesn't work

### ISSUE THREAD

**Issue by Ectalite** [powercord-org/powercord#280]
I installed the latest beta of Discord Canary and wanted to start it. Discord works 2 seconds before displaying a uniform gray screen. 

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows 10 latest slow insider version (19041.21)
 - Discord and Powercord version: Discord: Release Channel: canary, Build Number: 53613

**Additional context**
 Console: 
[Pastebin https://pastebin.com/idv65Hcf](https://pastebin.com/idv65Hcf)

**Comment by cyyynthia** [comment]
This is a known issue, however the hotfix is only available on development branch for now, and I can't merge them into stable v2 rn. You can switch to development branch by executing the command `git checkout v2-dev` in Powercord's install folder

**Comment by Ectalite** [comment]
Ok thanks, I though it was because of the beta version I couldn‘t click on links but it seems to be my theme. 

30 janv. 2020 à 19:27 de notifications@github.com:
