### ISSUE TITLE
[Feature Request] Customized splash screen

### ISSUE THREAD

**Issue by resucutie** [powercord-org/powercord#296]
**Describe the feature request**
Customized splash screen

**What Plugin would it be for?**
Btw no plugin, but an in-built powercord feature

**Expected behavior**
When you open discord, it shows that annoying spalsh screen with an animated logo of discord and... its so annoying see that black bg and... it'll be cool if we can change it

__How it is injected__
It loads a css/scss file indicated by the theme(s) that the user is using. Like something:
* Main-file.css
* Splash.css (file loaded on splash)
* `powercord-manifest.json`

Things that need to have:
* Transparency auto-enabled bcs sharped edges are good
* Very fast css injecting because yes™

##### Tip: MasicoreLord#5338 found the splash window

**Comment by cyyynthia** [comment]
Themes can now apply to splash screen as of latest v2-dev :tada: (not yet documented)
