### ISSUE TITLE
[Spotify] Song name

### ISSUE THREAD

**Issue by localcc** [powercord-org/powercord#300]
**Describe the bug**
When reloading discord and then waiting for a little bit of time, song name changes to my discord username

**To Reproduce**
Start music in spotify
Reload discord
Wait a little bit
![DiscordCanary_aNnM4xjEKx](https://user-images.githubusercontent.com/42898191/75666609-c50fc080-5c7e-11ea-8b11-40e96b762ece.png)

**Expected behavior**
Music title should not change to my username

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Discord and Powercord version: [Release Channel: canary - Discord's Build Number: 55393 - Powercord's git revision: 420a7fd6032410c41ffa28e8e672fe9e8333989f@v2]

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme

**Comment by gradypaulson** [comment]
cannot reproduce. 

OS: Windows 10 Home
Discord & Powercord Version: Discord Build Number - 55393, Powercord git revision - [0cc721d]@v2-dev

**Comment by zziger** [comment]
can reproduce. bug appeared after leaving hibernation

OS: Windows 10 Pro
Discord & Powercord Version: Release Channel: canary, Build Number: 55991, Version Hash: 3cfa91c09a31978ddd68cadfd1e8296c8ec6c3c4, Powercord's git revision 43fd242

![image](https://user-images.githubusercontent.com/27638710/76764435-1fd40c80-6795-11ea-8649-dbcf33fbf6df.png)

**Comment by zziger** [comment]
if i open server where i have custom nickname, song name instantly changes to your nickname on the server
![image](https://user-images.githubusercontent.com/27638710/76765157-3dee3c80-6796-11ea-817d-dc1c7e330eef.png)
when hovering over the nickname even if there is a custom nickname on server, nickname changes to your global nickname
![image](https://user-images.githubusercontent.com/27638710/76765221-55c5c080-6796-11ea-8507-6c56e6419606.png)
![5WXS9RQRAx](https://user-images.githubusercontent.com/27638710/76765311-7b52ca00-6796-11ea-8c74-eabecd06d6e0.gif)

**Comment by zziger** [comment]
figured out that nickname changes not instantly, but only when you move your mouse
