### ISSUE TITLE
Doesn't work with Glasscord

### ISSUE THREAD

**Issue by j0lol** [powercord-org/powercord#316]
**Describe the bug**
 Glasscord does not work when Powercord is installed

**To Reproduce**

1. Install Powercord
2. Add glasscord.asar to index.js
3. Boot Discord Canary

**Expected behavior**
 Proper launch

**Desktop (please complete the following information):**
- OS: Arch Linux, KDE Plasma 5, KWin WM/Compositor
- Discord version: Canary 58883 (6dea2a8)
- Glasscord version: 0.0.7.1 (Tried 0.0.6 too)
- Powercord version: v2 (2a48663)

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [ ] I made sure this is not related to an external plugin or a theme
 (not sure)

People at Glasscord told me this is a problem with Powercord, not Glasscord in this issue:
https://github.com/AryToNeX/Glasscord/issues/20

This would be nice if fixed :)
(even though they don't support canary)

**Comment by aetheryx** [comment]
I can spend some time on looking into this, but to me this looks like an incompatibility with Canary instead of an incompatibility with Powercord. Has anyone tried injecting Glasscord into Canary?

**Comment by j0lol** [comment]
I think I was injecting it fine, but i can test it (without powercord, just normal canary) if you like!

**Comment by cyyynthia** [comment]
I've done some progress regarding Glasscord integration in 18c9ac3362baf8691beb98bb40d9e699c9a5e0f4, however as mentionned in code there are some broken pieces of code within 0.0.7.1 release and 0.1 is not released yet due to possible bugfixes from the Glasscord devs.

**Comment by NyaomiDEV** [comment]
Hey there! I am the Glasscord developer. Let's work together to fix everything, okay?
Release 0.1 is near the corner, but I will send you a testing build if you need it.
If you need it, please add me on discord: AryToNeX#9646

**Comment by cyyynthia** [comment]
Alright, after some work on Glasscord's side Powercord is now compatible with Glasscord :tada: 

**BUT** when installing Glasscord you'll need to take an extra step for the meantime: before doing the instructions gave on Glasscord's README you'll need to edit the package.json Powercord created (in the app folder) and after the main property a "name" property. Powercord doesn't add it as it's not strictly required in order for Electron to work but it's a Glasscord requirement (as it's internally used to perform some compatibility things and more).

Make sure your package.json looks like this and Glasscord should be pretty simple to install:
```json
{"main":"index.js","name":"discord"}
```
Powercord will in the future add this property at inject time (Implemented in core-cleanup branch, see #330) but for now you'll need to follow those steps.

I'll keep this issue opened for now and will close it as soon as following classic Glasscord's basic installation guide is all you need to get it working

**Comment by NyaomiDEV** [comment]
the fun part of this issue ticket is that now bowoser is part of the glasscord team too

**Comment by cyyynthia** [comment]
We've finally released compatibility fixes on our side :tada: Glasscord should now be fully compatible with Powercord, **BUT** read the whole thing.

We had to add a new property to the package.json to allow Glasscord and its injection tool to properly inject in Discord. We've added that property, but previous installations didn't have it. HOWEVER:

## Windows and Mac users
You simply need to update Powercord and completely restart Discord. Powercord will migrate the package.json automatically without any manual intervention required.

## Linux users
If Discord is installed in a root-owned directory, Powercord won't be able to repair itself. You'll simply have to uninject and re-inject Powercord.

**Comment by NyaomiDEV** [comment]
# Linux users

Glasscord `master` (future release 1.0) takes account of your borked Powercord installations, so you can just use `master` or wait for a Glasscord update!
