### ISSUE TITLE
[Injector] Support Stable and PTB

### ISSUE THREAD

**Issue by cyyynthia** [powercord-org/powercord#32]

**Comment by aetheryx** [comment]
I have managed to write an injector that supports canary, stable, PTB and the overlay, but the primary issue right now is the stable build using node v7.4.0 - meaning, no object spread and no fs.promises. Basically the whole codebase has to be refactored for stable support.

**Comment by aetheryx** [comment]
[experimental-stable-ptb](https://github.com/aetheryx/powercord/tree/experimental-stable-ptb) branch now exists, but overlay support is a WIP

**Comment by cyyynthia** [comment]
After further internal discussion, we decided to drop stable support. Powercord will stay Canary-only, and if people want to use it they'll have to use that client channel instead. If people wants to use it with other channels, they are free to try but we'll not provide any support for that kind of use.
