### ISSUE TITLE
Powercord doesn't start.

### ISSUE THREAD

**Issue by jakecolon3** [powercord-org/powercord#323]
**Describe the bug**
Powercord doesn't start, seems to be a problem with `(Drive):\Users\User\powercord\src\Powercord\apis\settings` from the console.

**To Reproduce**
Reload Discord.
**Expected behavior**
Powercord should start, not basic Discord.

**Desktop (please complete the following information):**
 - OS: Windows.
 - Discord and Powercord version: Running `powercord.buildinfo` returns `undefined`.

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme
 
Looks like it's a universal problem.

**Comment by lanye74** [comment]
Yeah this happened to everyone, to fix you need to go back to your installation directory, `cd powercord`, then `npm run unplug`, `cd ../`, delete the folder, `git clone https://github.com/powercord-org/powercord.git`, `cd powercord`, `npm run plug`

**Essentially, `cd` into your powercord directory with your terminal, unplug and quit discord, then do a fresh install.**

**Comment by jakecolon3** [comment]
Yes I know, just wanted to open an issue about it since there wasn't one already.
