### ISSUE TITLE
Classes for the current window state

### ISSUE THREAD

**Issue by resucutie** [powercord-org/powercord#328]
**Describe the feature request**
A feature for themes that adds classes about the window state (for ex, when the window is maximized, powercord adds a class called `maximized`)

**What Plugin would it be for?**
Utility Classes

**Expected behavior**
It simply adds classes in `body` element for the current state of the window: if transparency is enabled, if the window is maximized, etc.

**Comment by cyyynthia** [comment]
I don't think there are any use case for those (i can eventually see for transparency), but not for the window state. Can you maybe provide us some use cases you're thinking about?

**Comment by resucutie** [comment]
Well when you maximize the window in windows, for example, the maximize icon changes. In case of discord, no. Other example with maximized window is when transparency is enabled and you add very s_N_exy border-radius to the window itself, but well it will be strange if the window is maximized and the border-radius still there.

Btw sorry for my baguette engrish.
