### ISSUE TITLE
Translator plugin unavailable

### ISSUE THREAD

**Issue by cyyynthia** [powercord-org/powercord#335]
**Describe the bug**
The translator plugin is currently unavailable. A rewrite of it is planned due to the codebase being a huge pile or garbage and having tons of glitches.

**Desktop:**
Not relevant for the case

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme
 
This is a known issue that's been going on for the past few months, but I'm opening an issue here for tracking purposes.

**Comment by cyyynthia** [comment]
Built-in translate module is now scheduled for deletion as a community made plugin exists for it and has been receiving quite a lot of positive feedback: https://github.com/KyzaGitHub/message-translate. Use this plugin if you want the translation features (considered as beta by the author, be careful :test_tube:

**Comment by m1ksu** [comment]
> 



> Built-in translate module is now scheduled for deletion as a community made plugin exists for it and has been receiving quite a lot of positive feedback: https://github.com/KyzaGitHub/message-translate. Use this plugin if you want the translation features (considered as beta by the author, be careful 🧪

Getting a 404 on that link. Is an equivalent plugin available anymore?

**Comment by Vendicated** [comment]
https://github.com/cyyynthia/message-translate
