### ISSUE TITLE
Get rid of Electron's remote

### ISSUE THREAD

**Issue by cyyynthia** [powercord-org/powercord#337]
Just now, Discord released an update **forcefully disabling** Electron's remote module. This was fixed a few minutes later in Powercord through f8180d3ca86f027f4d3102b3b34c3f774239d1a9, however this raises a severe concern over this module we should take into consideration as soon as possible.

For the next couple days and probably months, we're pretty safe leaving this enabled, however Electron announced they'll completely get rid of it in next releases, which will have the same impact but won't be able to be hotfixed in a few mins.

While getting rid of the remote in core Powercord modules should be relatively easy and straightforward, getting rid of it on other places like plugins might be another story. For example, some plugins makes use of the remote to create BrowserWindow (like Multitask or Powercord's SDK).

Right now let's consider we are in the investigating part, where we have to evaluate the amount of work required to get rid of remote, what Discord APIs provide (might be interesting to give a look at the `DiscordNative` global), and what APIs we might need to implement for other plugins.

**Comment by TTtie** [comment]
I'll take this ;)

**Comment by MeguminSama** [comment]
Keep in mind, Discord are updating to Electron 9 soon(tm) so make sure to check any features that might be deprecated in electron 8 and 9.

**Comment by cyyynthia** [comment]
Most of our Electron calls are just remote calls, which is why it is a major concern right now. As far as I'm aware we don't use anything else deprecated (or planning to be enter a deprecation phase). However, if you found something please bring it to our attention so we can update to non-deprecated tehc
