### ISSUE TITLE
React Dev Tools on Linux

### ISSUE THREAD

**Issue by A5rocks** [powercord-org/powercord#339]
**Describe the bug**
The download url is for Windows.

**To Reproduce**
Use Linux.

**Expected behavior**
React devtools should be exist.

**Desktop (please complete the following information):**
 - OS: Linux
 - Powercord version: Revision f8180d3, but I checked and it's in the latest commit on both `v2` and `v2-dev` (not sure which one is bleeding-edge).

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme
 
https://github.com/powercord-org/powercord/blob/v2-dev/src/Powercord/plugins/pc-reactdevtools/index.js#L59
https://github.com/powercord-org/powercord/blob/v2-dev/src/Powercord/plugins/pc-reactdevtools/index.js#L68

I patched it manually, just replacing `win` with `linux` and it works:
![image](https://user-images.githubusercontent.com/40616000/84290606-dcfcb780-ab7e-11ea-8616-b8070203a88a.png)

**Comment by cyyynthia** [comment]
This has always been working for me and I'm on Linux (and it actually used to be Linux-only). Are you sure you properly followed the instructions gave by the plugin (Restarting Discord and/or closing and reopening devtools) before?

**Comment by A5rocks** [comment]
Okay I retried the repro, and it didn't work? I know for certain that the dev tools weren't shown before, maybe some weird caching thing on my end? Sorry :')

**Comment by cyyynthia** [comment]
Yeah our current implementation is fucky wucky and stuff like this can easily happen. I plan on redoing the way we load React DevTools in the client (and also offer an option to use the standalone version as well). For now it works good enough in most cases with the occasional glitches
