### ISSUE TITLE
Top bar of the window does not show up

### ISSUE THREAD

**Issue by withmask** [powercord-org/powercord#344]
**Describe the bug**
The top bar of the new window, sometimes does not show up, so you can't close nor minimize the window.

**To Reproduce**
It happens sometimes randomly, but when pc get an update (any) it gets fixed :thinking:

**Expected behavior**
The top bar should show and be able to be used

**Desktop (please complete the following information):**
 - OS: Linux
 - Powercord version: f8180d3

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme

**Comment by cyyynthia** [comment]
On Linux Discord trusts the window manager to show up its own topbar as it is not rendered through Discord. I don't think we do anything that'd cause the topbar to randomly vanish though. What's your WM/DE, and do you happen to have any advanced setting tweaked (e.g. transparency)?

**Comment by withmask** [comment]
All settings are to default. Still the same issue.

![image](https://user-images.githubusercontent.com/44925389/84934736-a91a1880-b0cf-11ea-9c18-ddbb956d68b9.png)

**Comment by withmask** [comment]
And it's working again for some reason. Guess i can close this.
