### ISSUE TITLE
Plugins listed under "Debug Information" within the Updater settings are not separated

### ISSUE THREAD

**Issue by Fyko** [powercord-org/powercord#349]
Hello! I was going to PR this myself but wasn't entirely sure about how to do it.
The "bug" (more or less formatting problem) is as described in the title

Photo:
![image](https://user-images.githubusercontent.com/45381083/85931770-05c1c400-b884-11ea-9886-873a20605961.png)
Element:
```html
<div class="full-column">Plugins:
badges-everywherelyricstwemoji-but-good</div>
```

**Comment by cyyynthia** [comment]
Thanks for reporting! I'll push a fix in a few minutes, as this is a relatively easy fix.
