### ISSUE TITLE
Discord.bio connection like github

### ISSUE THREAD

**Issue by xcruxiex** [powercord-org/powercord#351]
**Describe the feature request**
Just like the github connection added by powercord, have it be able to send you straight to your/user-in-interest's profile in your broswer. 
![image](https://user-images.githubusercontent.com/59365159/86496375-1935c900-bd75-11ea-85cd-8e400c453d85.png)

**Comment by ghost** [comment]
there is a plugin for this
https://github.com/Ser-Ames/discord-bio

**Comment by Kanin** [comment]
Also please use the [Suggestions repo](https://github.com/powercord-community/suggestions) for stuff like this

**Comment by cyyynthia** [comment]
This already exists as a plugin: https://github.com/Ser-Ames/discord-bio

Also, for requesting plugins please refer to https://github.com/powercord-community/suggestions as this repository is mainly for Powercord's core feature and internal APIs, and to give a look to the #plugin-links channel in our Discord server to see what's available.

**Comment by xcruxiex** [comment]
Ah my bad, sorry. Will do next time!
