### ISSUE TITLE
Linux installer doesn't like non-standard discord paths

### ISSUE THREAD

**Issue by oatmealine** [powercord-org/powercord#352]
**Describe the bug**
When installing on Linux with a non-standard Discord path (eg. /usr/share/discordcanary/ instead of /usr/share/discord-canary) the installer doesn't give an option to select your own path or even a descriptive error, and instead returns

`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined`

The process detection has to fail for the installer to try to use the legacy method, but i'm not sure what exactly made it fail on my end

**To Reproduce**

1. Close Discord
2. Move Discord from whatever directory its installed to to a different path
3. Try to install Powercord

**Expected behavior**
Instead of giving an error, the installer should let the user enter their own path when a valid one isn't found, or at least handle Discord not being found and tell the user an error saying so.

**Desktop (please complete the following information):**
 - OS: Solus x86_64, Linux 5.6.18-156.current
 - Powercord version: Doesn't apply

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme

**Comment by Weilbyte** [comment]
Opened a PR for this. Hopefully, they'll take a look :)
