### ISSUE TITLE
Changing branch breaks Powercord

### ISSUE THREAD

**Issue by ghost** [powercord-org/powercord#357]
**Describe the bug:**
Powercord crashes discord when switching from stable branch to development branch via the button. Once it finished, it won't be able to start with Powercord injected anymore.

**To Reproduce:**
You need to be on the v2 branch and switch to v2-dev on a new fresh clean (Button and via console end in the same result). After a while Discord will reload and it'll stay a gray rectangle instead of loading Discord. If you try opening Discord again you will get this error
![image](https://user-images.githubusercontent.com/48446328/87722562-9b33e200-c7b8-11ea-8501-45559b25cb96.png)
Changing your general Powercord settings lets you switch just fine.

**Expected behavior:**
You successfully switch to v2-dev and Discord starts normally.

**Desktop:**
 - OS: Windows 10 64-bit 1909
 - Powercord version: Revision: [f8180d3]

**Additional context**
 - [X] I checked if Discord and/or Powercord are up to date
 - [X] I made sure this is not related to an external plugin or a theme

**Comment by cyyynthia** [comment]
This is not related to the branch change flow. This is from ongoing rewrite that's not finished yet and that's why dev branch is not named stable.
