### ISSUE TITLE
Spotify Modal Controls Not Appearing

### ISSUE THREAD

**Issue by valentinegb** [powercord-org/powercord#362]
**Describe the bug**
There are no controls on the Spotify Modal, no matter if advanced controls are on or off. It only shows the cover, artist, and song name. If I hover over it, I am shown the progressed time. The following is a screenshot of what the Spotify Modal looks like for me:
![Spotify Modal](https://i.imgur.com/ERNlapm.png)

**To Reproduce**
I installed Powercord today. The only changes I have made is changing the cover to be square and linking my Spotify account on the website and in the app.

**Expected behaviour**
I expected the modal to appear as follows (With advanced controls off):
![Expected Result](https://camo.githubusercontent.com/dabf29565356e150e0bb69458b867e8156e735e9/68747470733a2f2f646973636f72642e636f666665652f3239386661352e706e67)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Powercord version: f8180d3 on the v2 branch

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme
 
I am disappointed that this feature is not functioning properly, as I switched from BetterDiscord to Powercord entirely because of the Spotify features.

**Comment by cyyynthia** [comment]
did you look at our FAQ in our Discord Server? Make sure this doesn't apply to you

> **__Why are there no control buttons on the Spotify module?__**
To control your Spotify playback we use Spotify's "Connect Web" API, which is unfortunately locked to Spotify Premium users. In order for you to control Spotify's playback you'll need to get a Premium subscription.
> 
> If you do happen to have a Spotify Premium subscription but you're still not seeing the buttons show up, it might happen that Spotify is reporting inaccurate data about your Premium status and alters the availability of the buttons. Try changing the playback in any way (play, pause, change track, ...) to trigger and update and let us get accurate data from Spotify.
> 
> If this still did not fix it, make sure you're not in a private session as we've received a few reports saying this causes your Premium subscription status to not be properly sent to us. Also make sure you do have your Spotify account linked to your Discord account (You can tell Discord to not show it on your profile and not show the song you're listening to in your status, if you don't want to)

**Comment by valentinegb** [comment]
Ah... my bad. Really sorry about that.
