### ISSUE TITLE
Spotify Modal Doesn't Appear if Spotify is Opened/Playing Before Discord Opens

### ISSUE THREAD

**Issue by valentinegb** [powercord-org/powercord#363]
**Describe the bug**
Spotify Modal doesn't appear if Spotify is opened/playing before Discord opens.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Spotify
2. Open Discord
3. Play Music

**Expected behaviour**
The Spotify Modal appears and shows information regarding the currently playing song.

**Desktop (please complete the following information):**
 - OS: Windows 10 2004
 - Powercord version: f8180d3

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme

_(This could potentially be considered a feature request.)_

**Comment by rflinkss** [comment]
Is there a link that anyone can provide so i can install Spotify Modal?

**Comment by valentinegb** [comment]
> Is there a link that anyone can provide so i can install Spotify Modal?

It's a default plugin included with Powercord...

**Comment by valentinegb** [comment]
Two years later, huh
Well, bye lol
