### ISSUE TITLE
New command

### ISSUE THREAD

**Issue by MHSSupport** [powercord-org/powercord#373]
**Describe the feature request**
A clear and concise description of what the feature is.
a command for the main bot when u do {p}help
**What Plugin would it be for?**
Name of plugin if applicable
N/A {i think}
**Expected behavior**
a whomade command for plugins so it'll return the creator of the plugin/theme so for example: {p}whomade Mutuals Quick Ban

**Comment by LandenStephenss** [comment]
Or you could just look at the plugin page?

**Comment by Lizzy284** [comment]
yes, but i mean if this is not working for whatever reason

**Comment by LandenStephenss** [comment]
I see practically 0 reason for that, would just be a filler command almost. Even if you cared that much to make a command on it you could just go look at the manifest

**Comment by cyyynthia** [comment]
This doesn't have a lot of use and won't be part of Powercord core, as the Plugins UI exists. If you still want it, you can suggest it at https://github.com/powercord-community/suggestions
