### ISSUE TITLE
Infinite loading in popped out stream.

### ISSUE THREAD

**Issue by duumxh** [powercord-org/powercord#378]
**Describe the bug**
Popped out stream loads infinitely.

**To Reproduce**
Start watching someone's stream, then pop out the stream.

**Expected behavior**
Working popped out stream.

**Desktop (please complete the following information):**
 - OS: Windows 
 - Powercord version: v2-dev (b8a213a)

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme
 
Sound is still working tho.

**Comment by Ectalite** [comment]
Same error

**Comment by Ectalite** [comment]
Seems to work on latest stable release (rev. 411a347).
Discord canary 78004 
MacOS 10.15.7

**Comment by cyyynthia** [comment]
This seems to have been fixed either by Discord or due to some changes that happened in Powercord at some point in time.
