### ISSUE TITLE
Error in Windows Settings relating to "Open Discord" option

### ISSUE THREAD

**Issue by LeafyLuigi** [powercord-org/powercord#382]
**Describe the bug**
Other than saying "Error popup once triggered", I've got no idea what explicitly causes it. There's a screenshot of the error popup at the bottom of this report and nothing seems to be spat out to the console. 
[Cruxie](https://github.com/xcruxiex) has also stated that PowerCord no longer auto starts too.

**To Reproduce**
1. Be on Windows (or emulate it).
2. Open settings, navigate to "Windows Settings".
3. Toggle the first option, "Open Discord".
4. Somehow get an error message that the console can't track.

**Expected behavior**
No error popup and PowerCord to automatically boot with Windows.

**Desktop (please complete the following information):**
 - OS: Win10 64bit
 - Powercord version: Official - 5b75ce7 - v2-dev

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme
 

Screenshot of error message: 
![image](https://user-images.githubusercontent.com/13402990/90717842-139e2f00-e2a0-11ea-96d0-c750da4d8c39.png)

**Comment by LeafyLuigi** [comment]
Confirmed on e90e4cf
Exact same error message pops up

**Comment by LeafyLuigi** [comment]
Confirmed on f9b6bb6
Exact same error message pops up

**Comment by kpostekk** [comment]
Same here, even pulling latest fix (c35e8bd) dosen't solve issue.
![image](https://user-images.githubusercontent.com/30326322/100976569-069c0780-3540-11eb-8471-234d946b8383.png)

**Comment by cyyynthia** [comment]
Commit aef2e6b should solve this issue, let me know if you're still experiencing issues
