### ISSUE TITLE
Quick CSS Window pop out not spawning correctly

### ISSUE THREAD

**Issue by rosegayming** [powercord-org/powercord#385]
**Describe the bug**
Quick CSS pop out button spawns a blank window which cannot be closed or moved.
**To Reproduce**
Attempt to pop out Quick CSS windows
**Expected behavior**
Usable, popped out Quick CSS window
**Desktop (please complete the following information):**
 - OS: [Windows 10 Version 1909 Build 18363.1016]
 - Powercord version: Tested on Revision 41cb7ce (latest stable) and Revision 8ea3445 (latest dev)

**Additional context**
 - [X] I checked if Discord and/or Powercord are up to date
 - [X] I made sure this is not related to an external plugin or a theme

 [Video of the bug in action](https://files.catbox.moe/l8dfe1.mp4)

**Comment by rosegayming** [comment]
Fixed by 58de9f1

**Comment by cyyynthia** [comment]
This change hasn't been pushed to stable v2 yet; Leaving this opened until it gets rolled out.
