### ISSUE TITLE
[Feature Request] Plugin scanning and active domain blocking

### ISSUE THREAD

**Issue by sepruko** [powercord-org/powercord#389]
**Describe the feature request**
Plugin scanning and active domain blocking

**What Plugin would it be for?**
Any plugin to be installed and used with the Powercord modification for the Discord Canary client on Windows, MacOS and Linux.

**Expected behavior**
The Powercord Updater, since it already handles plugins directly when updating should also scan updates/plugins on first load before loading/reloading them. This idea comes to light based on recent events, where malicious code was pushed to a series of plugins which resulted in at least 1 token for a staff account on the Powercord Discord server being distributed to the wrong hands.

I am unsure how difficult it would be to read the code including any obfuscations to determine whether the code will attempt to create unwanted behavior when loaded in the client. As a fail-save, a plugin attempting to connect to an untrusted domain should be denied and the user served with a popup asking if they wish to let the plugin continue.  Again, I'm no genius and wouldn't know how hard this would be to implement, or if you're not already attempting to implement these into the client.

I thank you for your time.

**Comment by cyyynthia** [comment]
I'll close this as it should be tracked as part of #386. We can't exactly scan plugins or analyze their behavior on fly easily and they'd still be able to break through. Although night's issue brought internal discussions about how stuff is handled. It won't exactly be a watchdog and be composed of multiple layers but still should be tracked in the referenced issue.
