### ISSUE TITLE
[ Suggestion ] Make the Spotify Modal restart the song at a specific threshold

### ISSUE THREAD

**Issue by stayberri** [powercord-org/powercord#39]
Make it so that pressing the "previous" button while the song has a duration longer than a specific amount (say 5 seconds), it replays the song instead of playing the previous song.

so this would restart the song: 

![restart](https://vgy.me/IzAqxe.gif) 

and this would play the previous song:

![previous](https://vgy.me/zpi1G4.gif)

_excuse the last gif being weird, i can't record things properly._

**Comment by MrLar** [comment]
Wouldn't it make more sense to just mimic what the spotify client does? Which is that you have to press the button twice if the song has been playing for longer than 2 seconds for it to go to the previous song.

**Comment by MrLar** [comment]
Which essentially is just if it has been playing for longer than 2 seconds you repeat else go back
