### ISSUE TITLE
powercord unplugs at reboot

### ISSUE THREAD

**Issue by KraXen72** [powercord-org/powercord#395]
**Describe the bug**
every time i start the pc and launch discord for the first time, powercord isn't plugged it. i have to manually unplug and plug back in

**To Reproduce**
?? i just know some other person had the same problem in installation-support

**Expected behavior**
it should automatically plug itself in at discord launch

**Desktop (please complete the following information):**
 - OS:windows 10
 - Powercord version: [You can find it in the Updater tab, available in your settings]

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date - yes
 - [x] I made sure this is not related to an external plugin or a theme - shouldn't be, i reinstalled all themes and plugins but still
 
i am on canary discord and using branch v2-dev

**Comment by LandenStephenss** [comment]
Does it happen on stable branch? Could just be discord yeeting powercord out of existence, but not sure how to tell.

**Comment by cyyynthia** [comment]
I haven't seen any report of such happening to people. Try completely reinstalling Discord see if it helps.

**Comment by brenden7158** [comment]
I've had this same issue, sometimes it says, other times it doesn't. I just made a file that automatically runs the powercord command and reboots discord.

**Comment by KraXen72** [comment]
how do i make such file

**Comment by arrrnmp** [comment]
Make a bat file that has this
```
@echo off
npm run plug
taskkill /F /IM DiscordCanary.exe
discord.exe
exit
```

That will plug powercord kill discord, open it again and exit the batch file, u just need to make that file open everytime u boot ur pc

**Comment by ckainz11** [comment]
Same problem here. At first it was rare that it would unplug, now if i run plug again, discord has no more access to my mic and powercord isnt installed
