### ISSUE TITLE
When putting in the prefix for the bot (EG .help) auto complete does not show

### ISSUE THREAD

**Issue by Ashley284** [powercord-org/powercord#398]
**Describe the bug**
When putting in the prefix for the bot (EG .help) auto complete does not show
**To Reproduce**
idk if its just me, but just legit try to use the bot for me the auto scroll dont show
**Expected behavior**
the auto scroll to appear and show all the commands available
**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Powercord version: [You can find it in the Updater tab, available in your settings]
(d40440e)
**Additional context**
 - [yes ] I checked if Discord and/or Powercord are up to date
 - [yes ] I made sure this is not related to an external plugin or a theme
 
forgot to add this:
Canary 67763 (69a15bb)
Host 0.0.281
Windows 10 64-Bit (10.0.20215)
Powercord v2 (d40440e)

**Comment by DracoClaw** [comment]
I have the same issue. If you could fill out the Details, I'm sure it'll help out with fixing the issue.

Canary 67763 (69a15bb)
Host 0.0.281
Windows 10 64-Bit (10.0.18363)
Powercord v2 (d40440e)

**Comment by GreemDev** [comment]
Can reproduce.

Canary 68050 (deafbd8)
Host 0.0.282
Windows 10 Pro 64-Bit (10.0.19041)
Powercord v2-dev (d40440e)

**Comment by RynnoRK** [comment]
yup i have the same issue, it did work for a while but now it just stopped.

Canary 68063 (ae5c321)
Host 0.0.282
Windows 10 64-Bit (10.0.18363)
Powercord v2 (284a2ce)
