### ISSUE TITLE
Latest update prevents running Discord

### ISSUE THREAD

**Issue by ghost** [powercord-org/powercord#401]
I updated and clicked the restart button, causing this error to show.
![discorderror](https://user-images.githubusercontent.com/39559405/94351540-afe9ed00-0027-11eb-83be-86f40d296b45.png)

When I ran git pull and replugged, it decided to work. I am using [discord-canary](https://aur.archlinux.org/packages/discord-canary) from the AUR.

**Comment by NurMarvin** [comment]
Already fixed. `cd powercord && git pull`

**Comment by cyyynthia** [comment]
I blame git
update to latest and everything will be good

**Comment by ghost** [comment]
Wow, I didn't know that Github issues updated like that!
