### ISSUE TITLE
[Feature Request] Fix Discord's User Modal tab classes

### ISSUE THREAD

**Issue by MulverineX** [powercord-org/powercord#402]
**Describe the feature request**
CSS Class application on the user modal's tabs is broken & inconsistent, also styles are applied via an attribute. Please fix so themes can effectively theme the tabs.

**What Plugin would it be for?**
N/A

**Expected behavior**
The selected tab in the discord user modal consistently has the `selected` class (currently is buggy and doesn't always show up), tabs no longer have `style` attributes, instead getting their default styling applied properly through a stylesheet that has a lower priority than themes/CSS snippets.

**Comment by cyyynthia** [comment]
New versions of Discord now add an `aria-selected` attribute that consistently and accurately reports if the tab is selected.
