### ISSUE TITLE
Powercord Breaks Zalgo Text

### ISSUE THREAD

**Issue by worldeva** [powercord-org/powercord#403]
**Describe the bug**
Zalgo text appears a weirdly spaced, bolded text. It displays like this:
![image](https://user-images.githubusercontent.com/62271116/94484183-9d93be80-01a1-11eb-83f6-d4dfd48b44fd.png)

**To Reproduce**
New install of powercord on arch. No themes enabled. Copy and paste zalgo text from: https://lingojam.com/GlitchTextGenerator, and send, or have someone else send it to you.

**Expected behavior**
Zalgo text is displayed/obscured. Text should appear like:
T̷́͝h̴͐͘e̶̓̉ ̷͑̿q̶̽̓ǔ̴͝i̷͐͝c̸͑̒k̷͊͂ ̴͋́b̷̿͂r̶̾̿o̸͑͝w̶͒͘n̴̉̌ ̷͊͘f̸̛̓ô̵̍ẍ̵́́ ̵̎̒j̵̍͒u̸͂͂ṁ̵͘p̵͛̒e̴͒̓d̸̀̐ ̵̑̓o̸͑̾v̴̐̽ȅ̵̓r̷̉̈́ ̵̎͗t̴͑͘h̵͗͜è̶͆ ̶̈̐l̵̉̽a̶͌̿z̷̉́y̷̨̆ ̷̔̇d̶͍̄o̴͊́ǧ̴̉

**Desktop:**
 - OS: Arch Linux
 - Powercord version: Upstream: Official; Revision f06cb; Branch v2

**Additional context**
 - [+] I checked if Discord and/or Powercord are up to date
 - [+] I made sure this is not related to an external plugin or a theme
 
Notes:
Zalgo text works with "small text", so its strange that it only breaks on normal text.

**Comment by cyyynthia** [comment]
CNR; Latest Powercord

Tried sending from both Powercord and Discord Web (Stable); Both gave exact same result and displays as expected
![image](https://user-images.githubusercontent.com/9999055/94484605-fc2a5e00-01dc-11eb-8479-62d0648a0641.png)

**Comment by worldeva** [comment]
Further experimentation: Web version:
![image](https://user-images.githubusercontent.com/62271116/94490072-54486c80-01ab-11eb-8a7c-b7e63b2cbac5.png)

After experimentation, it seems to be a issue with discord itself, as the installed stable branch is also broken. I'm going to close this issue, apologies to Bowser65 for a miserror (it seems to have been broken in a recent discord update).
