### ISSUE TITLE
Windows AutoStart not working

### ISSUE THREAD

**Issue by TheMagBum** [powercord-org/powercord#405]
**Describe the bug**
When I boot my PC, I always get the error message when discord starts automatically

**To Reproduce**
- Add discord to autostart
- Restart Windows

**Expected behavior**
![image](https://user-images.githubusercontent.com/45709417/94553765-49e4ac00-0259-11eb-834b-b8e81c45019e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Powercord version: 
![image](https://user-images.githubusercontent.com/45709417/94553860-6c76c500-0259-11eb-8c80-d70d272472f8.png)

**Additional context**
 - [x ] I checked if Discord and/or Powercord are up to date
 - [ x] I made sure this is not related to an external plugin or a theme

**Comment by jaydns** [comment]
#382

**Comment by HerXayah** [comment]
can confirm here too

**Comment by cyyynthia** [comment]
Commit aef2e6b should solve this issue, let me know if you're still experiencing issues
