### ISSUE TITLE
LMGTFY tab still shows up in settings after disabling

### ISSUE THREAD

**Issue by Martmists-GH** [powercord-org/powercord#413]
![image](https://user-images.githubusercontent.com/16361449/96388603-46827780-11aa-11eb-9fd7-5953682a0b93.png)

**Comment by BenSegal855** [comment]
Did you try reloading?

**Comment by BenSegal855** [comment]
Upon looking at the code, the settings are never unregistered on unload. Reloading discord will fix your issue @MaryWeeb but the settings should be unregistered in pluginWillUnload.
