### ISSUE TITLE
Braintree analytics are not removed in no-track

### ISSUE THREAD

**Issue by relative** [powercord-org/powercord#417]
**Describe the bug**
Braintree analytics are not removed in no-track

**To Reproduce**
1. Open devtools
2. Navigate to the network tab in devtools
3. Open a payment window (ex. nitro subscription)
4. Observe that the client makes calls to client-analytics.braintreegateway.com

**Expected behavior**
The request should not be initiated.

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme
 
Blocking braintree analytics should not cause an issue (It is already blocked in [easyprivacy list](https://github.com/easylist/easylist/blob/5a1ba28a1f28bfd9c79462f00029fc27a136b977/easyprivacy/easyprivacy_thirdparty.txt#L446))

**Comment by MulverineX** [comment]
This should be fixed in Powercord Version 3 with CSP.

**Comment by relative** [comment]
> This should be fixed in Powercord Version 3 with CSP.

client-analytics.braintree.com is in Discord's CSP

**Comment by MulverineX** [comment]
Powercord's CSP will be custom, its not going to copy Discord's verbatim

**Comment by relative** [comment]
Wouldn't that go against the whole preserving CSP thing then?

**Comment by MulverineX** [comment]
Preserving CSP meaning having it enabled *at all*, because at the moment it's disabled.

**Comment by cyyynthia** [comment]
Once again speculating and making something sound official when nothing official has been said about it..

This will not be filtered using csp since this will just cause errors to spit out, which is not something good. There are plenty of other methods, way cleaner and efficient to prevent Braintree' analytics from being sent, which is what will be used to prevent those.
