### ISSUE TITLE
[Feature Request] Media API

### ISSUE THREAD

**Issue by MulverineX** [powercord-org/powercord#418]
**Describe the feature request**
Provides access to native media player API's and the app's chromium Media Session API.

**What Plugin would it be for?**
A rewrite of pc-spotify that provides support to all media players ([suggestion](https://github.com/powercord-community/suggestions/issues/234)). Native media player activity (rich presence) ([suggestion](https://github.com/powercord-community/suggestions/issues/236)). [Powerembeds](https://github.com/powercord-community/suggestions/issues/136) to add its music player to the system media session.

**Expected behavior**
Gives methods to read the current media session(s) metadata (native), send control events (play/pause/skip, native), and to send media session data through the app (Chromium API).

Relevant documentation:
- [Windows Media Playback](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback) - [Node API](https://github.com/NodeRT/NodeRT) (Library for using windows system API's based on .NET)
- [MacOS Media Player](https://developer.apple.com/documentation/mediaplayer) - Could not find a node API for this, might not have looked hard enough.
- [Linux MPRIS2 Protocol](https://specifications.freedesktop.org/mpris-spec/2.2/) - [Node API](https://www.npmjs.com/package/mpris) - A lot of players Linux music players, as well as browsers, implement this protocol, so it would provide a path for most players to be supported, with additional plugins if nessicary.

Linux players to special case if they don't implement MPRIS2: 
- [Foobar2000](https://www.foobar2000.org/) - [Original suggestion](https://github.com/powercord-community/suggestions/issues/129) - Can probably pull this off with the [web control plugin](https://github.com/hyperblast/beefweb) & a [PreMiD](https://premid.app/) presence (authorized to do fancy things like registering a better Media Session API with the browser) - Edits to this API are not needed

**Comment by MulverineX** [comment]
Before anyone states this, obviously this is pending v3.

**Comment by MulverineX** [comment]
Updated to include MPRIS2 now that I know its a protocol/standard, resolves [this suggestion](https://github.com/powercord-community/suggestions/issues/138)

**Comment by cyyynthia** [comment]
NodeRT as well as Apple' stuff require the use of native libraries with is strictly not possible in the environment Powercord lives in. Those two will not be implemented, at least as-is.

MPRIS2 relies on a dbus interface for communication with makes implementing this irrelevant compared to an actual dbus communication, and this is still pending drafting as most of v3 APIs.

**Comment by MulverineX** [comment]
Additional context for interested parties: node has had a problem with native code for a long time, the issue is primarily on Windows, because win32 C++ builds are proprietary, enormous, and not included in a standard installation. This also causes issues in other languages because a lot depend on the C++ compiler for various things (eg. last step in compilation).  There is a solution/path to take, but unfortunately, it is not easy to do or maintain on your own, and the automated tools that do exist are either just as complicated or add significant bloat. This is not an issue on standard Linux distros because UNIX C++ compilers are open, optimized, and preinstalled/commonly used, additionally, a lot of system API's are provided in a way that node can let regular JS do the work through sockets. This problem is slowly changing with WSL, but that is not something on a standard end-user machine. Another solution that some node modules are employing is precompiling every configuration, but this is a non-standard practice because many developers are not on windows, and the automated paths to this are relatively new, and Powercord doing this would be a significant time investment as well as complicated. Finally, any special system for this would be a significant scope that's not exactly reasonable for the core of a discord client mod.

**Comment by cyyynthia** [comment]
We cannot use node modules because we don't control the environment we live in (node version, app architecture). No need to add context over something already ruled not feasible and that will not be worked on.
