### ISSUE TITLE
Powercord not working whatsoever

### ISSUE THREAD

**Issue by Blessedwasnotfat** [powercord-org/powercord#434]
**Describe the bug**
Plugins and modules are not loading. Neither is powercord in the settings tab. It's just regular Discord.
Yes, I HAVE system requirements, this only stopped working today.

**To Reproduce**
Open up client
Look in settings

**Expected behavior**
Loads themes, modules, plugins, etc.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Powercord version: [Unknown, unable to check]
![image](https://user-images.githubusercontent.com/73258485/100815878-f33f4e00-3412-11eb-94be-6578062f379f.png)

**Comment by BenSegal855** [comment]
Did you try repluggging?

**Comment by ezist** [comment]
"Have you tried turning it off and on again?" (Yes, I know this isn't helpful.)

**Comment by aarock1234** [comment]
Same issue, tried replugging. Happens after update.

**Comment by BenSegal855** [comment]
Im dont think this is necessarily a powercord issue but either way please [join our discord server](https://discord.gg/nFRHhDk) so we can help diagnose the issue and fix it in a manner more efficient than GitHub comments.

**Comment by aarock1234** [comment]
> Im dont think this is necessarily a powercord issue but either way please [join our discord server](https://discord.gg/nFRHhDk) so we can help diagnose the issue and fix it in a manner more efficient than GitHub comments.

After I spoke to Ben I got the solution.

> git checkout v2 && git reset --hard && git

After that I unplugged and replugged. 

Hope that helps 👍🏽

**Comment by aarock1234** [comment]
@BenSegal855 Please close this issue if there are no further updates, it still is appearing at the top of my Github dashboard. 

Thanks :)

**Comment by BenSegal855** [comment]
> @BenSegal855 Please close this issue if there are no further updates, it still is appearing at the top of my Github dashboard.
> 
> Thanks :)

I dont have perms to close it and @Blessedwasnotfat has not stated it as solved for them. You can unsubscribe from it though as you issue has been solved.

**Comment by cyyynthia** [comment]
Any updates about this issue?

**Comment by cyyynthia** [comment]
Closing this as stale due to the lack of response.
