### ISSUE TITLE
Discord Crash

### ISSUE THREAD

**Issue by Ectalite** [powercord-org/powercord#450]
**Describe the bug**
Since last update of powercord/discord canary, Discord is crashing.

**To Reproduce**
1. I updated Powercord with the updater inside discord.
2. I made Discord reload, but it didn't wanted to start properly (gray screen).
3. I restarted Discord and it updated itself, after the update it crashed a first time.
4. I started it again and it applied other updates, Powercord was gone.
5. I repluged Powercord and discord started normal.
6. The interface of discord reloaded 2-3 times after the starting before crashing.

**Expected behavior**
Not crashing

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Powercord version: Last from updater

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme
 
I don't use any plugins and my theme never broke discord.

**Comment by cyyynthia** [comment]
This is not an issue with Powercord but with third party plugins. The only solution is to move all of the plugins you have installed out of the plugins folder, and add them one by one until you find the culprit.

If you have bdCompat installed, make sure to also ensure you don't have faulty plugins which causes Discord to crash by doing the same thing (moving them all out and adding them one by one until you find the one breaking).

Plugins that are known to cause crashes are Rich Quotes and Autoplay gif avatars, although they probably aren't the only ones. I don't have many info about how BD plugins can run, however you can still ask on our Discord server, as more and more people get to test if plugins run.

**Comment by Ectalite** [comment]
It's related to the plugins, but I didn't installed any plugins.
What I've found is when removing pc-spotify it stops crashing.

**Comment by xBiei** [comment]
For me Message Logger V2 Plugin (using bdCompat) was the crash issuer...

**Comment by BenSegal855** [comment]
> For me Message Logger V2 Plugin (using bdCompat) was the crash issuer...

Please note that MLv2 is a direct violation of our [guidelines](https://powercord.dev/guidelines). Do not expect any support for it or for us to look into fixing it.

**Comment by xBiei** [comment]
> > For me Message Logger V2 Plugin (using bdCompat) was the crash issuer...
> 
> Please note that MLv2 is a direct violation of our [guidelines](https://powercord.dev/guidelines). Do not expect any support for it or for us to look into fixing it.

It's ok I'm just sharing my solution, maybe they won't use MLv2 anymore ;)

**Comment by DylanTheCyanVA** [comment]
I tried, but I can't fix it because it keeps crashing in discord!

**Comment by Ectalite** [comment]
Same here,
I think discord broke powercord one more time...

**Comment by 0xnxmeless** [comment]
> Same here, I think discord broke powercord one more time...

This is easily fixable:
- Navigate to your `powercord` directory through the terminal (cmd, any Linux terminal, etc)
- Run `git pull`
- Run `npm run unplug`
- Run `npm run plug`

and your issue should be resolved.

**Comment by 0xnxmeless** [comment]
> I tried, but I can't fix it because it keeps crashing in discord!

Refer to my above reply
