### ISSUE TITLE
Quick CSS editor pop-out window not working

### ISSUE THREAD

**Issue by zt64** [powercord-org/powercord#451]
**Describe the bug**
When popping out the Quick CSS editor it opens the popout window but nothing is displayed in it. When the window is closed the settings still says that the editor is popped out.

**To Reproduce**
Steps to reproduce the behavior: Settings > Themes > Quick CSS > Popout editor

**Expected behavior**
Normally it should open and show the CSS code and close just fine.

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu 20.04)
 - Powercord version: V2 Revision 9671e9c

**Additional context**
 - [ :heavy_check_mark: ] I checked if Discord and/or Powercord are up to date
 - [ :heavy_check_mark: ] I made sure this is not related to an external plugin or a theme
 
Most likely caused by the recent Discord canary updates on host version 0.0.117 and 0.0.118.

**Comment by cyyynthia** [comment]
One of the last commits I've made today seems to have solved this issue. I was able to reproduce this morning, and it's now working on my end.
