### ISSUE TITLE
crashes when sending a message to a person who blocked you

### ISSUE THREAD

**Issue by sewnie** [powercord-org/powercord#457]
**Describe the bug**
i don't know how to describe this very clearly.

**To Reproduce**
send a message to a person who blocked you

**Expected behavior**
clyde sending me a message of not being able to send a message

**Desktop (please complete the following information):**
 - OS: Windows & Linux
 - Powercord version: 
 ```
 Upstream:
Official
Revision:
[472e4e2]
Branch:
v2 
Latest:
true
```

**Additional context**
 - [X] I checked if Discord and/or Powercord are up to date
 - [X] I made sure this is not related to an external plugin or a theme
 
information i got from launching it from linux:
```
Unexpected crash report id length
Failed to get crash dump id.
Report Id: 

Unexpected crash report id length
Failed to get crash dump id.
Report Id: 
[WebContents] crashed... reloading
https://canary.discordapp.com/app?_=XXXXXXXXXXX
```

information i got from inspecting element:
![image](https://user-images.githubusercontent.com/47404953/106365423-998dce00-6346-11eb-94e0-34de7c368dc3.png)

**Comment by cyyynthia** [comment]
Does the issue happen if you only have base Powercord plugins installed? (meaning, no additional plugins other than the ones that comes pre-installed with Powercord)

**Comment by sewnie** [comment]
it even happens when all of my plugins are disabled, including the core plugins that powercord comes with.
