### ISSUE TITLE
cannot send messages starting with forward slash character

### ISSUE THREAD

**Issue by ghost** [powercord-org/powercord#460]
**Describe the bug**
If I type a message that starts with a forward slash (`/`), pressing enter does not send the message.

**To Reproduce**
- Install Powercord.
- Type a message starting with the `/` character
- Press enter key on keyboard
- Observe as nothing happens.

**Expected behavior**
I expect the message typed in the message box to be sent.

**Desktop (please complete the following information):**
Canary 75982 (c83f1c0)
Host 0.0.265
OS X 10.14.6 (18.7.0)
Powercord v2 (9fab14d)

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme
 
Example message in chat box:
![image](https://user-images.githubusercontent.com/64013111/106913421-e0d7de00-66fb-11eb-937b-f3817f7e376a.png)

**Comment by cyyynthia** [comment]
This seem to be the intended behavior on Canary. I was able to reproduce on the web version.

**Comment by randomzigzag** [comment]
This does break any Powercord commands if your prefix starts with a `/`. (My prefix was previously `//`)

**Comment by ghost** [comment]
> This seem to be the intended behavior on Canary. 

Should I open a bug report with Discord, then? This seems like a very annoying intended behaviour.

**Comment by sewnie** [comment]
i can't confirm, doing this won't do anything on my side

**Comment by PandaDriver156** [comment]
It's possible to send the message by putting a backslash infront of the forward slash
![kép](https://user-images.githubusercontent.com/46034537/112880914-5d1eea00-90cb-11eb-90b0-bbc3e3fe7ded.png)

**Comment by cyyynthia** [comment]
This is a very poor workaround since 99% of the cases you need to send a message starting with / is to trigger a bot command, which is something that can't be done with this "trick".
