### ISSUE TITLE
 powercord.rpcServer missing listeners('string') and removeAllListeners('string')

### ISSUE THREAD

**Issue by Balint66** [powercord-org/powercord#461]
### Describe the bug
The lines couses pc-rpc plugin to crash:
https://github.com/powercord-org/powercord/blob/727a66a1fde5b2405285781faba257caa5bf7b2d/src/Powercord/plugins/pc-rpc/index.js#L24
https://github.com/powercord-org/powercord/blob/727a66a1fde5b2405285781faba257caa5bf7b2d/src/Powercord/plugins/pc-rpc/index.js#L33
https://github.com/powercord-org/powercord/blob/727a66a1fde5b2405285781faba257caa5bf7b2d/src/Powercord/plugins/pc-rpc/index.js#L34

### To Reproduce

* I started discord on win 10 with the latest powercord like: `DiscordCanary.exe --remote-debugging-port=9223 &`
* choose Discord
* The error is shown in the consol

### Expected behaviour

Not crashing the RPC module

### Desktop (please complete the following information):**
 * OS: windows 10
 * Powercord version: Powercord v2 (9fab14d)

### Additional context
 * [x] I checked if Discord and/or Powercord are up to date
 * [x] I made sure this is not related to an external plugin or a theme
 
#### Add any other context about the problem here.

commenting out the lines stops the plugin's crash. I don't really know if they are necessary functions or not.

**Comment by cyyynthia** [comment]
Those errors have been suppressed in a patch a while ago
