### ISSUE TITLE
Discord Canary not loading at all after plugging Powercord

### ISSUE THREAD

**Issue by ayukovt** [powercord-org/powercord#462]
My discord canary literally doesn't load at all after I plug Powercord into it. There's 2 discord canary processes after opening it (both taking like 30MB of RAM) but it stays on that and nothing shows up. Works completely fine after unplugging tho

**Comment by BenSegal855** [comment]
Please provide the requested information from our [issue template](https://github.com/powercord-org/powercord/blob/v2/.github/ISSUE_TEMPLATE/bug_report.md) and consider joining our [discord server](https://discord.gg/gs4ZMbBfCh) where we can give you more direct assistance.

**Comment by Balint66** [comment]
@takimikuu After you unplugged and you are sure that not a single discord process is running (if there is any, terminate them).
Then you should go to the directory where you have cloned powercord and run the command `git pull`.

This will get the newest code for powercord.
If it says there are some errors, make sure you backup your plugins somewhere and then `git stash` after that `git pull`.

Doing this and then plugging it worked in my case.

Next time please use the [issue template](https://github.com/powercord-org/powercord/blob/v2/.github/ISSUE_TEMPLATE/bug_report.md) to help the developers work.

**Comment by cyyynthia** [comment]
Any updates on this issue?

**Comment by ayukovt** [comment]
Problem fixed. Completely deleted powercord and downloaded it again and it plugged fine and discord opened.
