### ISSUE TITLE
[Feature Request] doas support

### ISSUE THREAD

**Issue by soup6020** [powercord-org/powercord#466]
**Describe the feature request**
Support for injection via doas

**Expected behavior**
An elevation method that is either sudo/doas agnostic, or having the injector runnable in an already elevated shell by checking SETUID or something.

**Comment by cyyynthia** [comment]
The injector in v3 will contain some changes and I want to ship with it a better elevation system, so I'll label this issue as some v3 stuff.

> or having the injector runnable in an already elevated shell by checking SETUID or something.

We [already check](https://github.com/powercord-org/powercord/blob/83f0aa39b61e725107fe312661b456940580dc1d/injectors/elevate.js#L10) for this, but npm v7 makes scripts run without privileges even if you're elevating npm. You can downgrade to an earlier version of npm (anything below v7 will do) if you absolutely need to.
