### ISSUE TITLE
Autocomplete crashes the client

### ISSUE THREAD

**Issue by userXinos** [powercord-org/powercord#473]
**Describe the bug**
If you use the command autocomplete the client crashes

**To Reproduce**
1. Type `.help `  (where `.` - default your prefix)
2. Press [Enter]

**Expected behavior**
So that the client does not crash

**Desktop (please complete the following information):**
 - OS: Linix Manjaro/Windows
 - Powercord version: `83f0aa3`

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme
 
*as a temporary solution, you can use: type the command manually completely and press the spacebar to out focus on the proposed elements*

**Comment by userXinos** [comment]
workaround for this bug for built-in plugin in #470

**Comment by cyyynthia** [comment]
PR has been merged
