### ISSUE TITLE
Builtin tags plugin breaks if a tag is created with name " "

### ISSUE THREAD

**Issue by alterae** [powercord-org/powercord#486]
**Describe the bug**
I somehow accidentally created a tag with the name " " (a single space character).  It is impossible to delete this tag.

**To Reproduce**
I'm not actually sure?
I typed `.tag add test` as far as I know, and it added a tag with the name " ".

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows
 - Powercord version: revision 61c8dae

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme
 
I am very sorry this bug report is not more useful.  I am irritatingly uncertain what actually happened.

**Comment by Vendicated** [comment]
Go into your powercord folder, open settings/pc-tags.json with your favourite editor and remove the line with the empty tag. Restart discord to apply the change

**Comment by alterae** [comment]
> Go into your powercord folder, open settings/pc-tags.json with your favourite editor and remove the line with the empty tag. Restart discord to apply the change

That worked, thank you!
