### ISSUE TITLE
[Feature Request] Details on what makes powercord lightweight

### ISSUE THREAD

**Issue by jacksongoode** [powercord-org/powercord#491]
Some brief documentation would be cool :+1:

**Comment by uBreeze** [comment]
honestly i know some people that picked up powercord because of that description and i did myself and i still have no fucking clue how powercord is any more lightweight

**Comment by cyyynthia** [comment]
There are things that are difficult to explain when "it just is that way"; no useless allocations, no memory leaks, no duplicate datastore, and that's p much it. We probably won't really make a documentation point or amend the homepage.

> I still have no clue how powercord is any more lightweight

We never claimed that powercord is *more* lightweight. BetterDiscord (once default stuff like BTTV emotes disabled) is likely to have the same footprint as Powercord.
