### ISSUE TITLE
Shows successful injection yet no powercord settings show up

### ISSUE THREAD

**Issue by ignaudioz** [powercord-org/powercord#492]
**Describe the bug**
Running plug will output injection was successful and tell me to restart discord completely which I did yet
discord seems to still be unplugged

**To Reproduce**
Plugging..

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Kernel: 5.11.15-arch1-2
 - Powercord version: no powercord to begin with..

**Additional context**
 - [ X ] I checked if Discord and/or Powercord are up to date
 - [ X ] I made sure this is not related to an external plugin or a theme
 
-  Running "yay powercord-git" won't do anything as well

**Comment by zt64** [comment]
What discord package did you install? It has to be canary, and the best one for it is discord-canary on the aur

**Comment by ignaudioz** [comment]
tried both the aur/discord-canary-electron-bin and the aur/discord-canary
same results on both

**Comment by zt64** [comment]
What version of node and npm are you using? Did you also plug it using sudo?

**Comment by ignaudioz** [comment]
> What version of node and npm are you using? Did you also plug it using sudo?

 npm: 7.11.0
 node: 15.14.0
 yeah and I did use sudo to plug

**Comment by ignaudioz** [comment]
Found the fix. 
I will explain how I found it here:
Removed discord-canary with yay
decided to find the left overs of the delete with find / -name "discord-canary" "
deleted them reinstalled discord-canary and boom its working.
