### ISSUE TITLE
[Wiki] Add AUR installation instructions

### ISSUE THREAD

**Issue by busybox11** [powercord-org/powercord#494]
I found myself failing to install powercord by using the `powercord` binary installed by the AUR.
I found out how to do it by looking at the code (`ls -la $(which powercord)`, `cat` the file) but I couldn't find any instructions anywhere.

**Comment by zt64** [comment]
Well, that AUR package isn't official and the recommended way is to clone with git and use `npm run plug`

**Comment by cyyynthia** [comment]
The AUR package is unofficial and already provides the [necessary documentation](https://aur.archlinux.org/cgit/aur.git/tree/powercord.8?h=powercord-git) which you can consult using the [manual](https://wiki.archlinux.org/index.php/man_page)
