### ISSUE TITLE
quick css deleted text when typing

### ISSUE THREAD

**Issue by doggybootsy** [powercord-org/powercord#500]
**Describe the bug**
acts like other text isnt there and deleted it

**To Reproduce**
use quick css

**Expected behavior**
to push the text not delete

**Desktop (please complete the following information):**
 - OS: OSX
 - Powercord version: 61c8dae

**Additional context**
 - [ x] I checked if Discord and/or Powercord are up to date
 - [ x] I made sure this is not related to an external plugin or a theme
 
video: https://imgur.com/a/g1JsEPF
plugins i have: F8Fix, pronoundb-powercord (still does it when there disabled)

**Comment by cyyynthia** [comment]
Did you by any chance press the insert key on your keyboard?

**Comment by doggybootsy** [comment]
its fixed now
but even if i push it, it doesnt do that.  
so im gonna close this
