### ISSUE TITLE
Uninstalling a plugin crashes the client

### ISSUE THREAD

**Issue by jayden000** [powercord-org/powercord#505]
**Describe the bug**
Client hard crashes and restarts when attempting to uninstall a plugin. This affects all plugins, at least the ones I tested (includes default and one self installed)

**To Reproduce**
1. Go to Powercord plugins
2. Try to uninstall any plugin

**Expected behavior**
The plugin uninstalls.

**Desktop (please complete the following information):**
 - OS: Windows
 - Powercord version: 8b6eb3d

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme

**Comment by jayden000** [comment]
Forgot to attach a screen recording.

https://user-images.githubusercontent.com/23621862/120261818-ae339180-c266-11eb-9e86-f1a00b27a33d.mp4

**Comment by jayden000** [comment]
https://user-images.githubusercontent.com/23621862/121096324-f94a2900-c7bf-11eb-8fe0-12eafc6eab66.mp4

**Comment by ifa-s** [comment]
I can confirm, I get the same result on my end.
Canary 87063 (417f3d7)
Host 1.0.35
Windows 10 64-Bit (10.0.19042)
Powercord v2 (48cbbf8)

**Comment by sewnie** [comment]
same results.
Canary 87274 (ba3997e)
Host 1.0.35
Windows 10 64-Bit (10.0.19043)
Powercord v2 (00f3d03)

**Comment by akisblack** [comment]
The uninstall button doesn't currently work, just delete the plugin's folder in files

**Comment by cyyynthia** [comment]
I'll consider this as a duplicate of #332 as the reason for the crash is this issue.
