### ISSUE TITLE
Not functioning as of latest Discord Canary update

### ISSUE THREAD

**Issue by RikuKawai** [powercord-org/powercord#506]
**Describe the bug**
Client is completely broken with powercord installed since the latest update today. Thinks it is running in a browser and the window cannot be dragged around nor have anything drag and dropped or right clicked in it. No powercord functions are operable.

**To Reproduce**
Install powercord on the latest Canary update. 

**Expected behavior**
For powercord to function correctly without breaking the client.

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2 19042.985 x64
 - Powercord version: None as it won't run properly, latest pull from github as of today.

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [X] I made sure this is not related to an external plugin or a theme

**Comment by WolfSkin0** [comment]
I can confirm the same on linux too, so it's not a platform issue.
Running 64-bit arch linux with kernel: 5.12.7-zen1-1-zen
Latest powercord version

**Comment by ThatOneCalculator** [comment]
Confirming as well, 64 bit Arch GNU/Linux on the Xanmod 5.12.8 kernel.

**Comment by MiincK** [comment]
Windows 10 x64 1909, same issue

![image](https://user-images.githubusercontent.com/25132061/120689962-589cf600-c4ad-11eb-90e1-1021993d0256.png)

**Comment by VelvetToroyashi** [comment]
Behold, [#known-issues on the discord](https://canary.discord.com/channels/538759280057122817/755012685963460620/850058946826862614)

**Comment by RikuKawai** [comment]
> 
> 
> Behold, [#known-issues on the discord](https://canary.discord.com/channels/538759280057122817/755012685963460620/850058946826862614)

This is not the most helpful input when the issue at hand is the Discord client not functioning correctly is it.

**Comment by nicolaspiet** [comment]
I have the same problem

**Comment by Yumiro** [comment]
Discord's latest host update broke Powercord, it's a (very) known issue and a lot of people in the support server have talked about it, please just wait for a Powercord update that fixes it. If the web client is really bothering you, just unplug Powercord and wait for an official announcement in the server.

**Comment by AtlasC0R3** [comment]
Okay, maybe someone should precise: **yes**, this is a well known issue being reported many, many times in the Powercord Discord guild. So far all we can do is wait, ~~or help Powercord by finding a fix and creating a pull request, which I honestly doubt would happen~~.
Quoting from aforementioned channel by VelvetThePanda:
> **Discord thinks it's running in a browser**
> Yes, we know. If it's bothering you, unplug powercord (`npm run unplug`) and it will go back to the normal desktop app. We'll have a fix for it when we're able.

Before anyone points fingers at anything, the new Discord client update is the main problem; as far as I can see, the Discord client changed something that Powercord used to, well, do the client mod thing. *And now I realized I'm too late to say all of this, oh well.*

**Comment by RikuKawai** [comment]
> 
> 
> Okay, maybe someone should precise: **yes**, this is a well known issue being reported many, many times in the Powercord Discord guild. So far all we can do is wait, ~or help Powercord by finding a fix and creating a pull request, which I honestly doubt would happen~.
> Quoting from aforementioned channel by VelvetThePanda:
> 
> > **Discord thinks it's running in a browser**
> > Yes, we know. If it's bothering you, unplug powercord (`npm run unplug`) and it will go back to the normal desktop app. We'll have a fix for it when we're able.
> 
> Before anyone points fingers at anything, the new Discord client update is the main problem; as far as I can see, the Discord client changed something that Powercord used to, well, do the client mod thing. _And now I realized I'm too late to say all of this, oh well._

Thank you for your input, not all of us are in the support server and I'm just doing my due diligence to report that Discord broke something. As far as I could tell from the issues here on the repo I thought I was the first to report this.

**Comment by ThatOneCalculator** [comment]
Works now, pog
