### ISSUE TITLE
Powercord won't start at all since latest update

### ISSUE THREAD

**Issue by ghost** [powercord-org/powercord#507]
Doing npm plug it says to restart, i do it, and Discord doesn't even show the window.

**Comment by ghost** [comment]
Temporary Fix
-
Run `git pull && npm run unplug && npm i && npm run plug`

![image](https://user-images.githubusercontent.com/78124644/120706387-efb77d00-c4b0-11eb-9856-eda0193859b2.png)

**Comment by ghost** [comment]
Done that and it doesn't work.

**Comment by ghost** [comment]
Once i do npm run plug discord starts in background but there's no window.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/16446639/120715463-e89a6a00-c4c4-11eb-9dfd-23d780badc83.png)
 That 's what  happens, discord running in Background, but no window

**Comment by ghost** [comment]
Try opening Discord from your system tray.

**Comment by ghost** [comment]
i did everything, it stays stuck like that, until i run unplug.

**Comment by aoqia194** [comment]
@xAstroBoy try again. I had the same problem, but they released a fix. So, `git pull` should fix it. Running that fixed it for me.
EDIT: You forgot to run `npm run unplug`. You did `git pull` + `npm i` + `npm run plug` but didn't do `npm run unplug` before running `npm i`.

**Comment by aoqia194** [comment]
This should be closed now.

**Comment by ghost** [comment]
@codexecYT i did all of the steps and it still won't work.

**Comment by cyyynthia** [comment]
You either aren't closing discord properly, or you have an unsupported installation of Discord that is not pulling from this repository. Either way, your case is isolated so this is something for our support server (and I know you are in there) rather than the issue tracker.
