### ISSUE TITLE
Code mirror has no vertical scrollbar

### ISSUE THREAD

**Issue by doggybootsy** [powercord-org/powercord#508]
**Describe the bug**
code mirror doesnt have vertical

**To Reproduce**
make css thats bigger than the code mirror window

**Expected behavior**
to have a vertical scrollbar

**Desktop (please complete the following information):**
 - OS: osx
 - Powercord version: [48cbbf8]

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme
 

I have no themes enabled and all pc plugins and the theme toggler plugin.
https://user-images.githubusercontent.com/71196819/120874155-1bdb0880-c55a-11eb-8be5-f52a89b9b268.mov
also does it in the themes tab but a little bit different behavior

**Comment by MulverineX** [comment]
Can reproduce on both popup & settings, on PopOS/Ubuntu 20, powercord 48cbbf8.

**Comment by arrrnmp** [comment]
Can reproduce on popup, Arch Linux 5.12.9-zen1-1-zen, powercord 48cbbf8

**Comment by Leo40Git** [comment]
Can reproduce on both popup & settings, on Windows 10, Powercord 671cea6

<details>
    <summary>Screenshot</summary>
    <img src="https://user-images.githubusercontent.com/7997354/123442418-89200d80-d5dd-11eb-977a-3fb973a962cf.png" />
</details>
