### ISSUE TITLE
[Suggestion] Badges for certain users

### ISSUE THREAD

**Issue by stayberri** [powercord-org/powercord#51]
Next to certain users names, there should be badges. For example,
Developers [aeth and maybe bowser]
Contributors [gord, nycex]
Beta Testers [myself, basically all users in Aetheryx' Hub who use PC right now]
Bug Hunter [self explanatory, maybe only give out for more major bugs and not visual things, but up to you]

In addition, maybe per-user tags for users? e.g: right click kosame#3658 -> add tag -> "stupid"
when kosame#3658 next speaks:
```
kosame#3658 (BADGE IF APPLICABLE) [stupid]
```
idk just an idea, but this issue mainly is for the first half of this

**Comment by cyyynthia** [comment]
Partially landed in https://github.com/aetheryx/powercord/commit/907d981f204acc8ecb35630252ced49980fa337c with Powercord badges

![uwu](http://breaking-discord.is-my-k.ink/accc758c8a.png)
