### ISSUE TITLE
Discord app thinks its running on web

### ISSUE THREAD

**Issue by thunderstorm010** [powercord-org/powercord#510]
**Describe the bug**
When powercord is plugged, sometimes discord thinks its running on web and the window controls disappear.
Unplugging powercord resolves the problem, so its not a problem with the discord client.

**To Reproduce**
I don't know how this happens. I have no plugins except the default ones.

**Expected behavior**
The app behaving like its running on desktop, with window controls.

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Powercord version: Don't know; no powercord menus when plugged.
 - Discord version: Canary 87279

**Additional context**
 - [ ❓ ] I checked if Discord and/or Powercord are up to date
 Can't check, no menus or anything indicates the powercord version, Discord Canary is up-to-date.
 - [ ✔ ] I made sure this is not related to an external plugin or a theme

**Comment by thunderstorm010** [comment]
Its a duplicate, sorry.

**Comment by arrrnmp** [comment]
Check #known-issues channel

**Comment by Randomx24** [comment]
restart powercord.
