### ISSUE TITLE
Spotify plugin interface bug

### ISSUE THREAD

**Issue by JacquesHumule** [powercord-org/powercord#512]
The spotify plugin interface don't work properly
![image](https://user-images.githubusercontent.com/32205945/121775900-6ed04380-cb8a-11eb-84ef-d8762dd00188.png)

I don't know but it's alway donig that even if i unplug/plug powercord

The icon mustn't be vertically aligned but horizontaly aligned

 - OS: Windows
 - Powercord version: f876037

**Comment by cyyynthia** [comment]
Try to follow the steps described in #known-issues in our support server

**Comment by JacquesHumule** [comment]
What steps ?

**Comment by authorisation** [comment]
try disabling your themes

**Comment by JacquesHumule** [comment]
it changes nothing

**Comment by cyyynthia** [comment]
Fixed a few days ago by 0cbdc63b8bf6af0ae3038f0005be595b1162de1c
