### ISSUE TITLE
[Feature Request] Allow registering command icons

### ISSUE THREAD

**Issue by boehs** [powercord-org/powercord#514]
**Describe the feature request**

![](https://e.reeee.ee/0A3vdV.png)

I want to be able to set custom icons for commands and whatnot

## The ~~two~~three options

1. Module based icon
2. Command based icon
3. Somehow both?

### The both route

1. Sidebar icon is module icon
2. Each command can have its own icon that is shown when you are entering command arguments.
3. If not specified, defaults to module icon

## Sidenote

This might already exist but due to lack of documentation I can't find it

**Comment by cyyynthia** [comment]
Powercord uses the legacy way command used to work, and there's no icon to set there. There is no plan to migrate to slash commands in v2, as it's maintenance only while v3 is in the works.

**Comment by boehs** [comment]
> Powercord uses the legacy way command used to work, and there's no icon to set there. There is no plan to migrate to slash commands in v2, as it's maintenance only while v3 is in the works.

I see, and V3 will use / commands for this, correct?
