### ISSUE TITLE
Plugin suggest not working anymore

### ISSUE THREAD

**Issue by SharkLava** [powercord-org/powercord#516]
**Describe the bug**
Autocomplete for commands like echo emotes and mock are not working
**To Reproduce**
type prefix

**Expected behavior**
list of commands 
**Desktop (please complete the following information):**
 - OS: Linux(Manjaro stable)
 - Powercord version: Upstream Revision 671cea6 branch v2

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme(as far as i know the only external plugins i have installed are the kaomoji and upload to cloud plugin)

**Comment by Leo40Git** [comment]
This is a known issue (check the Discord server's #known-issues channel).
