### ISSUE TITLE
Client restarts while interacting with blocked messages

### ISSUE THREAD

**Issue by boofiboi** [powercord-org/powercord#522]
**Describe the bug**
Client restarts while interacting with the "XXX blocked messages -- click to view" message

**To Reproduce**
Go to a DM where you have a person blocked
Click on view blocked messages

**Expected behavior**
being able to see all the messages

**Desktop (please complete the following information):**
OS: Windows
Powercord version: 6d2ce66

**Additional context**
 - [X] I checked if Discord and/or Powercord are up to date
 - [X] I made sure this is not related to an external plugin or a theme
 

Pretty weird bug, happens in every DM/server i go to

https://user-images.githubusercontent.com/79476279/124924936-ce1a4b80-dfb0-11eb-9fc0-237b6f7b3a90.mp4

(Excuse the Osu!, I found the bug while playing :D )

**Comment by cyyynthia** [comment]
Are you sure this is not related to a plugin you have installed?

**Comment by boofiboi** [comment]
> Are you sure this is not related to a plugin you have installed?

![image](https://user-images.githubusercontent.com/79476279/124926523-7a106680-dfb2-11eb-8b04-05e1ef9ac8ad.png)

**Comment by cyyynthia** [comment]
I cannot reproduce the issue.

**Comment by boofiboi** [comment]
not my problem

**Comment by cyyynthia** [comment]
It just means it's likely to be a plugin you have installed that causes a crash. Instead of ticking boxes without doing any check and sending a screenshot of you ticking the box, you should maybe consider I'm asking for a reason.
