### ISSUE TITLE
Powercord account unable to link

### ISSUE THREAD

**Issue by brandon-gable** [powercord-org/powercord#530]
I try to link my powercord account. It opens the page and it says i can close it, but it doesn't link. I'll try again and keep getting a message saying "linking flow timed out".
![image](https://user-images.githubusercontent.com/76926600/128095595-e7a4a021-5bef-4423-9afb-f692c7cc4bae.png)

**Comment by BenSegal855** [comment]
Use a different browser.

**Comment by cyyynthia** [comment]
This is a known issue and depends on the browser and/or browser settings set, caused by how we handle linking. We won't rewrite the logic in v2 so this will remain a bit hacky like it is right now.
