### ISSUE TITLE
Discord seems to crash when accessing "guilds" (servers)

### ISSUE THREAD

**Issue by Melodycloudu** [powercord-org/powercord#531]
Just got Powercord installed on a new install and I have done powercord's installation correctly but the client seems to just break when accessing Servers it just shows this screen 
Extra info: I have Powercord running on a separate drive to my discord install (this might be the issue?)
![image](https://user-images.githubusercontent.com/51493662/128185294-f020d54f-55a6-4d0c-bcae-e9e38ff5fb04.png)

**Comment by cyyynthia** [comment]
This is not a Powercord issue, Discord has released a broken version of Canary. They'll most likely fix the issue shortly.

**Comment by Melodycloudu** [comment]
tbh I aint surprised i had issues when i was installing canary again with it being "corrupt" after a fresh install
