### ISSUE TITLE
powercord failing to hook and crashing canary

### ISSUE THREAD

**Issue by MultipedBeatle** [powercord-org/powercord#532]
I started Discord, and it kept crashing when I tried to access a server. I have to close out of the app completely in Task Manager to get back to the app, and when I checked my settings I noticed that none of my Powercord settings were showing up. My themes loaded but not the application itself.

I have no way of checking the Powercord version because of the lack of it working lol. I'm on Windows 10.

Also, if when I launch and before I try to access a server, I could try to hit the green update button before it crashes if that would help.

**Comment by MultipedBeatle** [comment]
browser discord works fine, so its not an issue with servers or something like that. also means my account is okay.

**Comment by Afootpluto** [comment]
it is issue with canary discord. It crashes even with powercord unplugged.

**Comment by Beppe1509** [comment]
happening to mee to :(

**Comment by MrBoombastic** [comment]
Yup, it's crashing with Powercord unplugged on Canary 92322 (0daffd7).

**Comment by cyyynthia** [comment]
Duplicate of #531
