### ISSUE TITLE
Quick CSS causing client crash

### ISSUE THREAD

**Issue by NYRI4** [powercord-org/powercord#533]
**Describe the bug**
Trying to open the Quick CSS in a different window is causing the crash of the client.

**To Reproduce**
Go in your settings and open the Quick CSS in a popout.

**Expected behavior**
The Quick CSS opens in a popout without causing the client crash.

**Desktop (please complete the following information):**
 - OS: Windows
 - Powercord version: 28fdee6

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme
 

https://user-images.githubusercontent.com/65369563/128380516-df95fd97-ed8a-4fb3-9417-7c89e36a5695.mp4

**Comment by NYRI4** [comment]
Well, looks like the video isn't working, here's a screenshot before the client crash

![mpc-be64_c0ApBa3pPE](https://user-images.githubusercontent.com/65369563/128381263-39fcfe44-215a-4a45-aa6f-c5cdb9b32454.png)

**Comment by DracoClaw** [comment]
Same here.

Canary 93578 (1b9c859)
Powercord f45939d
Windows 10

**Comment by Wolfkid200444** [comment]
Same thing happening here

Canary 93654 (7a8d1cb) 
Host 1.0.37 
Windows 10 64-Bit (10.0.19042)
Powercord (f45939d)

**Comment by ItsJunction** [comment]
Same here

Canary 93654 - 7a8d1cb
Powercord - f45939d
Windows 10 Home 64 Bit

EDIT: Mine isn't due to the css, cause is unknown.

**Comment by ivan123-tty** [comment]
Same here. 

Canary 99582 - 30eedd9
Powercord - 737d091
Windows 10 Home 64-Bit (20h2)

cause is also unknown.

**Comment by NYRI4** [comment]
The issue still remain the same for me (for informational purposes)

Canary 99843 (f01cd2e)
Powercord - [`f01cd2e`](https://github.com/powercord-org/powercord/commit/737d09139c06b1b48450a6c8086f101ecfd5d780)
Windows 10 64-Bit (10.0.19043)

https://user-images.githubusercontent.com/65369563/135533344-e536f77d-3297-4074-863e-ba0e274d202c.mp4

**Comment by ivan123-tty** [comment]
> Same here.
> 
> Canary 99582 - 30eedd9 Powercord - [737d091](https://github.com/powercord-org/powercord/commit/737d09139c06b1b48450a6c8086f101ecfd5d780) Windows 10 Home 64-Bit (20h2)
> 
> cause is also unknown.

![image](https://user-images.githubusercontent.com/70339505/135660191-41d52723-2655-4dd8-a7e7-367d3c4f2ec3.png)

**Comment by ghost** [comment]
There is an issue in the code with the popout so dont use the popout for now lol use the default tab without popping it out!
![image](https://user-images.githubusercontent.com/56656809/138555122-3574906c-25f5-45b3-9990-275862e3cf82.png)
