### ISSUE TITLE
Question about  ./i18n/overrides/

### ISSUE THREAD

**Issue by Szafranek13** [powercord-org/powercord#538]
Can you translate the whole discord to the language that doesn't have translation yet this way? And if yes, how to find entry names like `OPEN_IN_THEATER` in ` "OPEN_IN_THEATER": "Open in Theatre",`?

**Comment by cyyynthia** [comment]
In theory, yes, in practice not really. Discord has thousands (9000+) of strings with new ones added or edited on a daily basis. It'd also require a little bit of patchwork in some places. Messages can be found from Discord's source code or by poking at the i18n engine.
