### ISSUE TITLE
short description of bug

### ISSUE THREAD

**Issue by worbgge** [powercord-org/powercord#545]
**Describe the bug**
running discord-canary gives an error and can not start

**To Reproduce**
run discord-canary in the terminal

**Expected behavior**
get and error about launching the app, the error is 
```
[~] discord-canary
Error launching app
Unable to find Electron app at /usr/lib/discord-canary/app

Cannot find module '/usr/lib/discord-canary/app'
Require stack:
- /usr/lib/electron/resources/default_app.asar/main.js
-
```
Taking the advice of another github pull request: https://github.com/powercord-org/powercord/pull/442#issuecomment-862044499 it says to change .asar to just app
```
[~] discord-canary
Error launching app
Unable to find Electron app at /usr/lib/discord-canary/app.asar

Cannot find module '/usr/lib/discord-canary/app.asar'
Require stack:
- /usr/lib/electron/resources/default_app.asar/main.js
-
```

this started messing up when the new discord-canary package changed to community; https://archlinux.org/packages/community/x86_64/discord-canary/ 

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64, 5.13.12-arch1-1
 - Powercord version: most recent

**Additional context**
 - [ /] I checked if Discord and/or Powercord are up to date
 - [ /] I made sure this is not related to an external plugin or a theme

**Comment by huantianad** [comment]
I believe #442 is for the `discord-canary-electron-bin` package on the AUR, not `discord-canary`

**Comment by obj-obj** [comment]
Try running `sudo chmod --reference=/usr/lib/discord-canary/bootstrap /usr/lib/discord-canary/app && sudo chmod --reference=/usr/lib/discord-canary/bootstrap/manifest.json /usr/lib/discord-canary/app/*`
