### ISSUE TITLE
[Feature Request] (powercord/http) Set headers for all requests instead of for every request

### ISSUE THREAD

**Issue by flleeppyy** [powercord-org/powercord#559]
**Describe the feature request**
I make a lot of requests to an API in a plugin, and I would like to have an already set header for my bearer token so I don't have to do this for every request I make

```js
let res = await get(this.api_endpoints.me)
          .set("Authorization", "Bearer " + this.settings.get("apitoken")); // this line
```

**What Plugin would it be for?**
Plugin's that use an external api that require authorization, or having pre-set headers in order to access the url

The way it would work would be similar to Axios, [Creating an instance](https://axios-http.com/docs/instance). It should still work with any plugins that don't need to set headers beforehand.

**Concept**
```js

// In this example, `http` now has a create function, similar to axios's create function.
const http = require("powercord/http")

/**
 * http.create would return what `require("powercord/http")` returns,
 * but the headers and baseUri (Which does not exist but could be implemented)
 * would be set already, so there's no need to do something like
 * await get("blahblah/aaaa")
 *  .set("Authorization", "Bearer ba7fb39bc9ab3AAAAAAAAA")
 */ 
const { get } = http.create({
  headers: {'Authorization': 'Bearer asdfghjkl12345678901234567890ASDFGHJKLzxcvbnM,'},
  baseUri: "http://localhost:8085/api"
})

await get("me/notes")
```

If I have some time, I could make a PR to implement it

**Comment by cyyynthia** [comment]
Due to Powercord's current state we will not be accepting new features, and this is one. We also won't make it part of v3 as we simply replace `fetch` in plugins by a custom `fetch` implementation transparently, nothing more.

It's also easy to go around this by just importing `get` from `powercord/http` as a different name, and making a `get` function (or method on your class) that does the the wrapping.

```js
const { get: httpGet } = require('powercord/http')

function get (url) {
  return httpGet(`http://localhost:8085/api/${url}`).set('authorization', 'Bearer xxxxx')
}
```

**Comment by cyyynthia** [comment]
I'll also add to it that it's a more dynamic approach and allows to take into account instantly token changes in settings (as it seems it's from where you're pulling the token), whereas a statically initialized instance is frozen and has to be fed with new data manually.
