### ISSUE TITLE
Powercord no longer loading on Canary e8bc079 (Windows)

### ISSUE THREAD

**Issue by cryptofyre** [powercord-org/powercord#564]
**Describe the bug**
Powercord does not load after updating Discord to the latest canary build. I've tried unplugging and plugging again to no avail. However during loading window time the theme definitely applies just nothing reaches the true client.

**To Reproduce**
Update Discord.
Powercord does not get injected.

**Expected behavior**
Powercord should have been injected at startup.

**Desktop (please complete the following information):**
 - OS: Windows 11 (22483.1000)
 - Powercord version: Latest commit

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme

This error seems to be caused by Webpack 5.

**Comment by RaspberryKitty1** [comment]
discord updated to webpack 5 breaking PC

**Comment by Schleifenkratzer** [comment]
is there a way to downgrade discord up until its fixed?

**Comment by MulverineX** [comment]
Other than using Stable with another Client mod, at the moment, no.

**Comment by tandpfun** [comment]
There looks to be some sort of extra anti-abuse thing built into the webpack, running things with the above getModules script (and other similar stuff) seems to set the timestamp language to Klingon 😂
![image](https://user-images.githubusercontent.com/28990589/138392336-bb301c72-3e68-4a23-9e52-ceed41d4ce1c.png)

**Comment by DOTD100** [comment]
stupid question but how did you get that to run?

**Comment by tandpfun** [comment]
> stupid question but how did you get that to run?

Run the above code to add the function and:

```js
getModules('webpackChunkdiscord_app').find(m => m?.default?.getUser).default.getUser('userid')
```

**Comment by DOTD100** [comment]
No I meant, where do I run it

**Comment by RedDaedalus** [comment]
You run it in the dev console (ctrl+shift+i)

**Comment by DOTD100** [comment]
aight, thanks

**Comment by twnlink** [comment]
yeah, it's not an anti-abuse mechanism the code is just bugged. will quickly find a fix :)

**Comment by twnlink** [comment]
fixed the code :)

**Comment by DOTD100** [comment]
typed it in console and I'm getting undefined

**Comment by twnlink** [comment]
> typed it in console and I'm getting undefined

i keep fucking with it, it should be perfect now (won't mess with it anymore)

**Comment by twnlink** [comment]
type in `modules` and hit enter

**Comment by twnlink** [comment]
you skipped the part where you run `getModules(webpackChunkdiscord_app)` but even then that won't fix your problem

**Comment by cyyynthia** [comment]
Fixed in b146edf. Powercord might not start up if you have an outdated version of Better Status Indicator; for all other plugins impacted by the update they should just malfunction until you receive an update through the updater without any severe impact.

**Comment by JonasBBX** [comment]
still not working linux

**Comment by x86-39** [comment]
Works again for me after pulling https://github.com/powercord-org/powercord/commit/1d2318bcd7c5e5a5230d8bf25813ed648cfd7b76
The extension https://github.com/powercord-community/channel-typing was causing it to not launch, but pulling https://github.com/powercord-community/channel-typing/commit/8e41b085410a5bb72ddf9f372c8957eed6d2cb82 there fixed that issue too.

OS: Fedora 34

**Comment by MrCheeze446** [comment]
works for me as well on endavourOS

**Comment by ghost** [comment]
Zorin os and win 10 you just have to update powercord
