### ISSUE TITLE
Powercord fully unplugged and still crash/boot loop

### ISSUE THREAD

**Issue by BotterManTingGoes** [powercord-org/powercord#565]
**Describe the bug**
A recent canary update broke powercord, powercord devs then told users to `git pull` to update and fix the problem,  I did so and then canary crashes repeatedly, so I unplug fully and canary still crashes even after fully quitting canary and removing plugins.

**To Reproduce**
Steps to reproduce the behaviour: git pull, load up canary, crash.

**Expected behaviour**
git pull to fix the recent canary update that broke powercord, load up canary and for it to not crash.

**Desktop (please complete the following information):**
 - OS: w10 21H1
 - Powercord version: Can't load it up to find out however from this post it is the latest.

**Additional context**
 - [X] I checked if Discord and/or Powercord are up to date
 - [X] I made sure this is not related to an external plugin or a theme

**Comment by nate-moo** [comment]
This is happening to me too

**Comment by Catalyst4222** [comment]
I'm also experiencing this issue

**Comment by 12944qwerty** [comment]
Try removing the plugins that has been reported broken in #known-issues on discord that haven't been fixed.

The plugin that I removed was bdcompat and it worked for me

**Comment by Catalyst4222** [comment]
~~Yes, join the server when discord won't load~~

Thanks, that worked! Had to remove 4 of my favorite plugins though

For those who don't want to join the server, here's the list as of time of writing:
```
better replies (has update)
channel typing (has update)
fix user popouts (has update)
multitask (has update)
pronoundb for powercord (has update)
rolecolor everywhere (has update)
toprole everywhere (has update)
total members (has update)
wallpaper changer (has update)
better status indicators (crashes discord) (has update)
cutecord (has update)
discordbio
guild profile (has update)
report message
ownertag (has update)
bdcompat (has update, bd plugins still liable to crash)
user-details (crashes discord when opening a profile)
owner-tag (has update)
betterquoter
```

**Comment by ghost** [comment]
make sure to remove bdcompact and open your console when you load up discord using ctrl shift i and look at what plugin doesnt load and remove it. It can cause the injector to crash bc it wont locate the plugins / or because they are outdated.

**Comment by 12944qwerty** [comment]
Bdcompat is now fixed and shouldn't affect anything. BD plugins may cause crashes though so be wary.
user-details and betterfriends are the ones you should remove now (I think those are the only two reported to crash)
