### ISSUE TITLE
Still not installable after new canary update

### ISSUE THREAD

**Issue by ShadiestGoat** [powercord-org/powercord#566]
**Describe the bug**
I updated discord canary, and powercord to latest commits, removed everything possible & re-plugged this bad boy, yet it doesn't load. Theres no errors reported. If opening discord through terminal I get the following:

![image](https://user-images.githubusercontent.com/48590492/138596368-52c6e71f-ba67-4d0f-a2af-484e09735dcc.png)

No mentions of powercord within the discord console. I tried using this directly from github & using powercord-git on the AUR, theres no difference.

**Expected behavior**
Powercord to plug & work

**Desktop (please complete the following information):**
 - OS: Arch linux, 5.14.12-arch1-1
 - Powercord version: Latest commit.

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme

**Comment by madonuko** [comment]
how did you re-plug powercord?

**Comment by ShadiestGoat** [comment]
`sudo npm run unplug && sudo npm run plug`

I also tried removing all of discord && powercord file. And using `sudo npm run plug`

**Comment by madonuko** [comment]
1. go to the powercord directory (sth like `cd powercord`)
2. `git pull`
3. quit discord entirely
4. `npm run unplug`
5. `npm run plug`

**Comment by ShadiestGoat** [comment]
Alrady tried that. Thats the first thing I tried lmao. I'm already at latest commit, I've plugged & replugged loads of times!

**Comment by ShadiestGoat** [comment]
Heya! I got it working again. I had to fully delete discord, as I was deleting the `/opt/discord-canary` location, but I had to delete the `/usr/lib64/discord-canary/`
