### ISSUE TITLE
opening src/Powercord/modules/ in Finder on macOS creates file, .DS_Store, causes powercord to crash on startup

### ISSUE THREAD

**Issue by ashy1227** [powercord-org/powercord#571]
**Describe the bug**
the finder app creates a file, .DS_Store in every folder you go into (yeah it's really not very smart), and powercord seems to think it's a module. it tries to load it, and obviously fails at doing so...preventing powercord from loading entirely and creating other (temporary) minor functional issues in discord

**To Reproduce**
simply opening up the modules folder is enough to do it

**Expected behavior**
PC should probably ignore non-modules and dotfiles

**Desktop (please complete the following information):**
 - OS: Mac
 - Powercord version: `Official 1d2318b v2` (up-to-date as of right now, not exaaaaaactly sure how to read these versions :p)

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme

**Comment by katlyn** [comment]
Fix should be as simple as adding an additional check to [src/Powercord/modules/index.js#L3](https://github.com/powercord-org/powercord/blob/6d6b4fd34ebbd59571f3e3eee1ca09ba17a78881/src/Powercord/modules/index.js#L3).

**Comment by FrimeX** [comment]
I added the fix to already open PR, See #572
