### ISSUE TITLE
[Feature Request] tags: fill in message bar instead of sending

### ISSUE THREAD

**Issue by asportnoy** [powercord-org/powercord#574]
**Describe the feature request**
Have a way to fill tag content in the chat box instead of just sending, potentially with a shortcut. This would allow us to edit the text before we send it.

**What Plugin would it be for?**
N/A

**Expected behavior**
Enter tag command like usual, press certain key or shortcut and the content is filled in your chat box.

**Comment by cyyynthia** [comment]
Tags allow use of special tokens `$$@` and `$$<n>` to have variable input in your tags. See https://github.com/powercord-community/suggestions/issues/410#issuecomment-834575354 for usage
