### ISSUE TITLE
themes not loading in 

### ISSUE THREAD

**Issue by anavinnit** [powercord-org/powercord#576]
most of the themes are not loading in I have kinda fixed it but I need more help fixing that

**Comment by anavinnit** [comment]
help

**Comment by ghost** [comment]
do you have multiple applied at once?
if so, powercord probably doesn't know which one to pick

**Comment by cyyynthia** [comment]
For support requests please join our [support server](https://discord.gg/powercord) and ask in the appropriated channel.
