### ISSUE TITLE
Menu goes out of screen

### ISSUE THREAD

**Issue by XeynQ4** [powercord-org/powercord#592]
**Describe the bug**
When I right click a user who's low on the page the menu goes out of the screen. When I hover over it, it moves the hole discord window up.

**To Reproduce**
Have enough plugins that add something to the user right click menu (maybe it works without it but I'm not sure).
Right click on users name or pfp in lower part of chat and the menu will go out of screen. When you hover over it, it will move the whole discord window up in order to be on screen.

**Expected behavior**
When I right click the menu should show up higher in order to stay on screen.

**Desktop (please complete the following information):**
 - OS: Windows 64-bit
 - Powercord version: 1d2318b

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme (I think it isn't)

https://user-images.githubusercontent.com/68696016/143462882-b02eaee9-87df-48a1-bc66-26edc3c8efae.mp4

**Comment by cyyynthia** [comment]
This is a bug with Discord, not Powercord itself.

**Comment by XeynQ4** [comment]
Is there no way I could fix it? if I would rewrite how discord choses what top to give to that div I think it could work. If you are sure it's impossible than ok but if it is possible I would like to maybe revisit it in the future when (if) I know a bit more about powercord.
