### ISSUE TITLE
Quick CSS does not retain after restart when installed via Pacman on Arch Linux

### ISSUE THREAD

**Issue by SkySpnc** [powercord-org/powercord#594]
Title is self explanatory; quick CSS does not save when installed via Pacman.
Expected behavior: quick CSS remains and is applied as usual after restart.
Actual behavior: quick CSS is lost when restarting discord.

https://user-images.githubusercontent.com/83870752/144691036-03bcb00e-4872-4bd8-8cf3-7cf9925f9fda.mp4

**Comment by cyyynthia** [comment]
The AUR package is not officially supported. Contact the package maintainers about it, this is considering how a package works and how Powercord handles saving quickcss "working as intended".

**Comment by viermat** [comment]
Manjaro user here, installed via `yay -S discord-canary`
Works perfectly fine for me, can't seem to reproduce.
