### ISSUE TITLE
Powercord crashing bug

### ISSUE THREAD

**Issue by omribashi** [powercord-org/powercord#596]
**Describe the bug**
If you go to the new server profiles feature and try to write a custom bio with powercord on, with each letter you will be forced out of the writing box. After you exit the entire window, discord will crash.

**To Reproduce**
- go to a server
- hit server profiles
- try to write a bio
- see what happens
- try and exit the window (I tried with saving changes)
- see what happens

**Expected behavior**
- you should be able to write with interruptions (tried on stable) and not crash. 

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]: Windows 10 64-Bit (10.0.19043)
 - Powercord version: [You can find it in the Updater tab, available in your settings]: 1d2318b

**Additional context**
 - [yes ] I checked if Discord and/or Powercord are up to date
 - [yes ] I made sure this is not related to an external plugin or a theme

**Comment by xPolar** [comment]
I'm able to reproduce this multiple times, system information below.
Canary 107563 (1fe8bb5) Host 1.0.42 Windows 10 64-Bit (10.0.2200
Powercord version 1d2318b

**Comment by kckarnige** [comment]
I am able to reproduce this aswell
Powercord commit 1d2318b on Windows 10
