### ISSUE TITLE
pc-emojiUtility sends invalid requests when cloning emotes

### ISSUE THREAD

**Issue by hexa0** [powercord-org/powercord#601]
**Describe the bug**
Whenever you attempt to clone any emote using pc-emojiUtility it fails with this error message:
![image](https://user-images.githubusercontent.com/67880600/148592151-fe917e3e-3554-43bc-beb9-1432e28adfad.png)

**To Reproduce**
Attempt to clone any emote with pc-emojiUtility

**Expected behavior**
The emote correctly uploads to the selected server

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 10.0.19042 Build 19042
 - Powercord version:
![image](https://user-images.githubusercontent.com/67880600/148592370-743e489c-f6b1-4154-9ce6-96d7f4fdf2c6.png)

**Additional context**
 - [Yes] I checked if Discord and/or Powercord are up to date
 - [Yes] I made sure this is not related to an external plugin or a theme

**Comment by faejr** [comment]
I seem to experience the same issue. Animated emojis do seem to be cloned correctly though.

Edit: Maybe it's cuz it's trying to clone it as a webp and upload which is not a supported format?

**Comment by calliah333** [comment]
Plugin loading seems to fail as well

![image](https://user-images.githubusercontent.com/35879391/152663517-95fbdf5b-30ac-44cd-bcf7-650d277ffd9e.png)
Which leads to 
![image](https://user-images.githubusercontent.com/35879391/152663521-602275ad-6bc0-4e46-8c70-71e78bbf7ae0.png)

I'm guessing that MessageContextMenu module got dropped in some update?

Seems like context menu injections are broken for all plugins. :/
