### ISSUE TITLE
Powercord couses API temporary ban on discord.

### ISSUE THREAD

**Issue by InfernoEye** [powercord-org/powercord#603]
After a lil bit of usage after the updated of discord messages stoped loading, then i couldnt load into discord. Dont install it for now.
npm run unplug and wait for the info from devs to actually work on it.

**Comment by cyyynthia** [comment]
This is due to a bad plugin rather than Powercord itself. Make sure you keep plugins up to date.

**Comment by InfernoEye** [comment]
All my plugins are up to date, don't close thread before getting to know anything.

**Comment by cyyynthia** [comment]
Powercord itself works fine and does not trigger any ratelimit by itself. Your thread is misinforming and spreading FUD while this is **not** a direct Powercord issue.
