### ISSUE TITLE
[Feature Request] Fix wayland screen sharing because upstream won't

### ISSUE THREAD

**Issue by reesericci** [powercord-org/powercord#606]
**Describe the feature request**
A clear and concise description of what the feature is.
It would be really cool if powercord could fix screen sharing on Wayland. (Linux)
**What Plugin would it be for?**
Name of plugin if applicable

**Expected behavior**
Discord screenshares via pipewire and the screencast xdg portal

**Comment by cyyynthia** [comment]
Duplicate of #555

**Comment by reesericci** [comment]
wow that was fast
