### ISSUE TITLE
a spammed error

### ISSUE THREAD

**Issue by xBiei** [powercord-org/powercord#607]
**Describe the bug**
Well actually it's just a report to what's happening in my console,
this error is spamming literally +100 times

**Desktop:**
 - OS: Windows 11
 - Powercord version: latest (29a69f9)

**Additional context**
 - [ x] I checked if Discord and/or Powercord are up to date
 - [ x] I made sure this is not related to an external plugin or a theme
 
![image](https://user-images.githubusercontent.com/65196493/149075336-3b5df2e4-c96b-439a-94b7-0dffc6f18d61.png)

**Comment by SammCheese** [comment]
:mmlol:
