### ISSUE TITLE
I can't install powercord!

### ISSUE THREAD

**Issue by aitronz** [powercord-org/powercord#613]
**Describe the bug**
I have much errors installing it!

**Expected behavior**
When I do the command **npm i** I see much errors in comand promt

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
 - [YES] I checked if Discord and/or Powercord are up to date
 - [YES] I made sure this is not related to an external plugin or a theme
 
Image of the errors
![image](https://user-images.githubusercontent.com/74368135/152862984-3aff5be8-2aa9-4218-a41f-c3aca552e6d1.png)

**Comment by colin273** [comment]
Installation support questions should be asked on Powercord's Discord server, not in GitHub issues. This is not a Powercord problem anyway; it's an NPM issue.

**Comment by cyyynthia** [comment]
For support requests please join our [support server](https://discord.gg/powercord) and ask in the appropriated channel.
