### ISSUE TITLE
Powercord crashing randomly on startup when Spotify is in the background (again with latest version)

### ISSUE THREAD

**Issue by QuiteAFancyEmerald** [powercord-org/powercord#623]
**Describe the bug**
Crash occurs on start up (again) if you are listening to a song on Spotify and I'm certain this is the latest version of Powercord. I am also certain this is the same error as before the fix that was done last week ago? Lastly I can confirm this is with Powercord only as I've run `npm run unplug` to verify that normal Discord works (which was the case).

Thanks!

**To Reproduce**
- Close current Discord/Powercord process via the system tray
- Startup Spotify in the background on PC (have the application installed) and play a song
- Open up Discord/Powercord as a new process and attempt to use the application
- App will show "Well this is awkward..." after around three seconds of usage 

**Expected behavior**
Discord app functions as usual with startup and Spotify running normally in the background.

**Desktop**
 - OS: `Windows 21H1 19043.1620`
 - Powercord version: Since the app is crashing I can't provide this. HOWEVER I have been doing git pulls and the crash still occurs so its the latest version
 
 Update (version): `2dc7ab1`

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme

**Comment by avail** [comment]
Are you running spotify? pc-spotify causes the crash

**Comment by QuiteAFancyEmerald** [comment]
That is... very odd. I am. Regardless this is still an issue since well I'm sure many people use Spotify so I guess we just found the issue?

Spotify on PC (or maybe just in general) DOES seem to crash powercord. WIll update this issue to reflect it.

**Comment by Tene21** [comment]
Same issue here, deleting the pc-spotify plugin stopped the crash but of course means that the spotify modal no longer works

**Comment by kekkodance** [comment]
wonder when a fix will come

**Comment by cyyynthia** [comment]
Fixed in 51e3f61125cf2545d505fe952bf2af8ae13ea0c9

**Comment by Tene21** [comment]
It seems like this issue has started occurring again recently
