### ISSUE TITLE
Newest Discord update creates null object errors

### ISSUE THREAD

**Issue by Lock-The-Door** [powercord-org/powercord#624]
**Describe the bug**
Many powercord plugins are facing null errors on injection including the command list popup

**To Reproduce**
1. Update to the latest discord version
2. Observe the breaking plugins (the null errors can be found in the console)

**Expected behavior**
Powercord injects its plugins normally and everything works

**Desktop (please complete the following information):**
 - OS: Windows
 - Powercord version: v2, revision 51e3f61

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme
 
**Error I got for the built in commands plugin**
```
Uncaught (in promise) TypeError: Cannot read property 'prototype' of null
    at Commands.injectAutocomplete (VM1181 C:\Users\...\powercord\src\Powercord\plugins\pc-commands\injectAutocomplete.js:158)
```

**Comment by GriefMoDz** [comment]
Thanks for the bug report. I'm here to inform you that a fix was previously implemented under this commit [here](https://github.com/powercord-org/powercord/commit/17b66335e85a613ca0ea66dcb95d2c676b0e2f03). For this reason I'll be closing this issue.
