### ISSUE TITLE
Hyperlink in Eradicate Clyde setting doesn't work

### ISSUE THREAD

**Issue by Duoquadragesimal** [powercord-org/powercord#629]
**Describe the bug**
The hyperlink does not work. The domain has been bought and it leads to a 404 page to a random website and not a discord wiki.
![image](https://user-images.githubusercontent.com/64324595/164385298-46dc062d-e1dd-4654-899a-fd784147dd1e.png)

**To Reproduce**
Settings > General settings > Eradicate Clyde > Click hyperlink

**Expected behavior**
Hyperlink shows a clyde wiki page instead of what appears to be a betting site

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Powercord version: b410b30 

**Additional context**
I don't know how to tick these boxes in markdown
 - [x] Yes, I checked if Discord and/or Powercord are up to date
 - [x] Yes, I made sure this is not related to an external plugin or a theme
 
could be fixed I think by replacing the url at line 42 of src\Powercord\plugins\pc-settings\components\GeneralSettings\index.jsx
(`          note={Messages.POWERCORD_SETTINGS_NO_CLYDE_DESC.format({ discordiaUrl: 'https://discordia.me/clyde' })}`)
replacing the discordia.me url with https://discord.fandom.com/wiki/Clyde#Bot

**Comment by adntaha** [comment]
The wiki seems to have been abandoned, so I believe it would be better to just remove the hyperlink.
