### ISSUE TITLE
The ui in the section settings is little bit bugged (see screenshot)

### ISSUE THREAD

**Issue by JOJOVAV** [powercord-org/powercord#630]
**Describe the bug**
I updated powercord manualy because it didn't update automaticly.
After the update I saw this in the settings.
https://i.imgur.com/YKSGKnD.png
https://i.imgur.com/20bw5Op.png
https://i.imgur.com/xyOqzyP.png
https://i.imgur.com/5HH1rNf.png

**To Reproduce**
up to date powercord

**Expected behavior**
the update page, clyde settings, plugin settings, css settings

**Desktop (please complete the following information):**
 - OS:Windows 10 v21H2
 - Powercord version: not availible (I think newest because I deleted my powercord and installed from fresh.

**Additional context**
 - [X ] I checked if Discord and/or Powercord are up to date (even installed from fresh)
 - [ X] I made sure this is not related to an external plugin or a theme

**Comment by BoredManCodes** [comment]
Duplicate of #627

**Comment by JOJOVAV** [comment]
> Duplicate of #627

Right forgot to search in here on the github 😅

**Comment by JOJOVAV** [comment]
closed because other one is open
