### ISSUE TITLE
Allow stable/PTB injection even though it is not supported

### ISSUE THREAD

**Issue by asportnoy** [powercord-org/powercord#632]
The README explains the reason for Powercord being canary-only is that internal differences could cause non-canary versions to crash. However, canary also frequently experiences issues with crashes when Discord makes a change.

Allowing Powercord to be used on these versions would be beneficial as canary has worse performance. In addition, the other versions could allow users to continue to use Powercord when canary breaks due to a Discord changes.

I propose you add an option to inject to non-canary versions, maybe with a flag on the plug command. This could contain a warning that non-canary versions may experience issues and support will not be provided.

**Comment by asportnoy** [comment]
@aetheryx could you clarify what extra help is needed? If it's just the code changes, I can do that and submit a PR.

**Comment by MulverineX** [comment]
Pretty sure that's what help wanted means, also to keep philosophy maybe this option can be marked as unsupported?

**Comment by asportnoy** [comment]
As I mentioned, using the option would give a warning that it may have issues and support will not be provided. I'll probably also add a confirmation prompt to make sure users understand it is unsupported.
