### ISSUE TITLE
[Spotify] Broken when streamer mode enabled

### ISSUE THREAD

**Issue by cyyynthia** [powercord-org/powercord#64]
Due to the fact that discriminator is missing in the user account info, so we can't get the style of it
`TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.`

**Comment by davidcralph** [comment]
on latest commit it seems to work fine for me :thinking:

**Comment by cyyynthia** [comment]
Try reloading while streamer mode is enabled. Since an element is missing
it fails and throws an error

**Comment by davidcralph** [comment]
oh, i see

**Comment by cyyynthia** [comment]
Updates on the issue: We do have kinda fixed it by using static value instead of fetching it dynamically. We do need a better fix and use dynamic values back, to ensure it'll work with custom themes or if Discord changes some CSS

**Comment by cyyynthia** [comment]
Fixed in #220
