### ISSUE TITLE
short description of bug

### ISSUE THREAD

**Issue by Ember-ruby** [powercord-org/powercord#648]
**Describe the bug**
The "Dismiss message" on ephemeral messages made by powercord or powercord plugins doesn't dismiss the message, it only dissapears after a discord restart

**To Reproduce**
Steps to reproduce the behavior: for example, use the tone tag plugin and click dismiss message

**Expected behavior**
The message should dismiss 

**Desktop (please complete the following information):**
 - OS: Linux
 - Powercord version: e5dbcc4

**Comment by FC5570** [comment]
Facing the same issue on windows too.

**Comment by 12944qwerty** [comment]
Known #629

**Comment by Ember-ruby** [comment]
> Known #629

I'm not sure how that's the same issue?
