### ISSUE TITLE
Opening LMGTFY settings from "Plugins" menu results a reload

### ISSUE THREAD

**Issue by DragonFire1230** [powercord-org/powercord#649]
**Describe the bug**
Go to Plugins and find LMGTFY plugin,
Opening settings of this plugin results a reload

**To Reproduce**
1.Powercord > Plugins
2.Find LMGTFY
3.Click "Settings" button
4.Discord reloads

**Expected behavior**
Opened settings of this plugin (Btw settings of this plugin exists)

**Desktop (please complete the following information):**
 - OS: Windows 10 19044.1706
 - Powercord version: Powercord v2 (8a47118) Official Repository

**Additional context**
 - [ Yes ] I checked if Discord and/or Powercord are up to date
 - [ (idk) i don't know ] I made sure this is not related to an external plugin or a theme
 

No error in JS console

**Comment by Captain8771** [comment]
the settings button in the plugins menu is from a plugin called better-settings

@mr-miner1 you might wanna see this

**Comment by mr-miner1** [comment]
hey, i looked into it a bit it seems the issue can be replicated with any default powercord plugin. ill add it to my bug fixing bucket list. till  then you can close the issue here and open it on the plugin repo https://github.com/mr-miner1/better-settings
