### ISSUE TITLE
[ Spotify ] Properly handle accounts that are not premium

### ISSUE THREAD

**Issue by MrLar** [powercord-org/powercord#65]
a.ka. grey out and disallow all features that use spotifies player API with some kind of thing mentioning you need to be premium.

**Comment by davidcralph** [comment]
maybe the thing mentioning you need to be premium should be the discord built-in notice? just a thought TM

**Comment by cyyynthia** [comment]
`getModuleByDisplayName('SpotifyPremiumUpgrade')`
