### ISSUE TITLE
Bug & Feature Request for non-canary notice banner

### ISSUE THREAD

**Issue by asportnoy** [powercord-org/powercord#660]
Bug: The close button does not show up (it still works if you click there, there's just no button)
![Screenshot on 2022-06-24 at 15 09 42](https://user-images.githubusercontent.com/14863373/175660332-2c8469fc-432a-49d6-b252-09524564612d.png)

Feature request: Add "Do not show again" button

**Comment by LeafyLuigi** [comment]
To add to the bug, the sidebar lacks a `hasNotice-` class to it after installation as well.
