### ISSUE TITLE
Powercord crashes after I right click on a user

### ISSUE THREAD

**Issue by djsawicko** [powercord-org/powercord#666]
**Describe the bug**
When I right click on a user, it shows this:
![image](https://user-images.githubusercontent.com/75716744/178117960-6477853c-095a-4895-a150-c114040a4db2.png)

**To Reproduce**
Plug powercord, open discord canary, enter a server and right click on it.

**Expected behavior**
The right click menu would pop up.

**Desktop (please complete the following information):**
 - OS: Windows 10, Build: 19044.1766
 - Powercord version: v2, 59df79d (Latest)

**Additional context**
 - ✔ I checked if Discord and/or Powercord are up to date
 - 🌗 I made sure this is not related to an external plugin or a theme
 - ✔ I have unpluged powercord and checked if it works, it does
 
Thanks in advance, sorry if this is unrelated.

**Comment by colin273** [comment]
Do you have `image-tools` installed? That plugin is known to still be causing crashes even with the latest Powercord update.

**Comment by djsawicko** [comment]
> Do you have `image-tools` installed? That plugin is known to still be causing crashes even with the latest Powercord update.

Yep, that was the issue, thanks
