### ISSUE TITLE
[Feature Request] Plugin to receive, and forward events.

### ISSUE THREAD

**Issue by devoxin** [powercord-org/powercord#69]
**Describe the feature request**
Perhaps a plugin for Powercord that can take standard Discord events, such as message create, and non-standard events such as a self-user mention and forward them to a given location, i.e. an IP address of a HTTP server that accepts payloads.

This server can then be coded to perform user-provided actions, in the case of a raspberry Pi it could perhaps activate a light strip for 3 seconds to indicate you've been mentioned.

**What Plugin would it be for?**
EventForwarder, idk

**Expected behavior**
Plugin receives MESSAGE_CREATE event (or non-standard event like when the current user is mentioned), and forwards a simple payload to a HTTP server located at a user-specified IP/domain. (i.e. POST `http://127.0.0.1/discord`, body `{ action: "MENTIONED" }`)

**Comment by katlyn** [comment]
for notifications (not all messages) this can be used (thanks aeth)
```javascript
const { getModule } = require('powercord/webpack');
const mdl = getModule(['makeTextChatNotification']);
mdl.makeTextChatNotification = (_makeTextChatNotification => (...args) => {
  console.log('gord code goes here');
  return _makeTextChatNotification(...args);
})(mdl.makeTextChatNotification);
```

**Comment by cyyynthia** [comment]
For Gateway messages you can just get them by doing `powercord.on('webSocketMessage:gateway.discord.gg', console.log)`
tho it's raw stuff so it needs to be decoded, and there is probably a way to inject somewhere to get them already decoded (or you'll have to decode them by yourself). I think aeth said something about a """""bot client"""" that would just be decoding that and re-mapping a client lib like Eris to use Discord internal functions

For other events it's mostly patching the right method, and you're good (see comment above)

**Comment by aetheryx** [comment]
to confirm, a fork of Eris' API for Powercord is in the works, and it will be undetectable and API-compliant

**Comment by cyyynthia** [comment]
So the issue 69  will be closed when the fork of Eris is live I guess

**Comment by thetakodev** [comment]
@Bowser65 ~~haha sex number~~

**Comment by cyyynthia** [comment]
Since it is possible to listen for gateway events through
`require('powercord/webpack').getModule([ 'dispatch', '_isDispatching' ], false).subscribe('EVENT_NAME', handler)`, can we close this issue?

**Comment by cyyynthia** [comment]
I'll consider we can safely close this, as you can easily subscribe to events within plugins through Discord's internals and if the point is to have a plugin forwarding events to an external source this'd belong to the [plugins suggestion repo](https://github.com/powercord-community/suggestions)
