### ISSUE TITLE
[Injector] Support multiple installation paths on Linux

### ISSUE THREAD

**Issue by ghost** [powercord-org/powercord#70]
I cannot inject Powercord into discord canary, the error I get is this one:
```
$ sudo npm run inject
[sudo] password for yanderella: 

> powercord@1.0.0 inject /home/yanderella/powercord
> node injectors/index.js inject

fucky wucky { Error: ENOENT: no such file or directory, mkdir '/opt/discord-canary/resources/app'
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/opt/discord-canary/resources/app' }
```
I expected powercord to inject successfully by the fact that I have followed all the steps

 - OS: Linux
 - Discord version: Canary 0.0.67

Also, I checked that specified folder and there isn't anything, I installed canary using dpkg via terminal.

**Comment by aetheryx** [comment]
can you locate the folder your discord install is at and what distro you use?

**Comment by ghost** [comment]
> can you locate the folder your discord install is at and what distro you use?

The folder where Canary is installed is this one: `/usr/share/discord-canary`, and I use xubuntu

**Comment by aetheryx** [comment]
https://github.com/aetheryx/powercord/blob/v2/injectors/linux.js you can change this to return `/usr/share/discord-canary/app` for the purpose of the install, we'll have to make the linux injector check for several paths and see which one is more up-to-date

**Comment by ghost** [comment]
> https://github.com/aetheryx/powercord/blob/v2/injectors/linux.js you can change this to return `/usr/share/discord-canary/app` for the purpose of the install, we'll have to make the linux injector check for several paths and see which one is more up-to-date

I have another problem, although the inject command runs successfully, Discord still remains normal, I restarted discord several times but this problem still appears.

**Comment by katlyn** [comment]
Did you make sure to do a full restart? eg Completely close out of discord and open again

**Comment by ghost** [comment]
> Did you make sure to do a full restart? eg Completely close out of discord and open again

I did, I even tried killing the process from the terminal just in case

**Comment by katlyn** [comment]
hm, that's a bit strange. In the dev tools are there any errors? also could you  run `powercord` in the devtools console to see if it's defined?

**Comment by ghost** [comment]
> hm, that's a bit strange. In the dev tools are there any errors? also could you run `powercord` in the devtools console to see if it's defined?

I get this error when I run `powercord`: 
```
VM354:1 Uncaught ReferenceError: powercord is not defined
    at <anonymous>:1:1
```

Excluding errors from spotify's api, I get this:
```
Uncaught (in promise) Error: /home/yanderella/.config/discordcanary/0.0.67/modules/discord_cloudsync/discord_cloudsync.node: undefined symbol: PKCS5_PBKDF2_HMAC
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602)
    at tryModuleLoad (internal/modules/cjs/loader.js:541)
    at Function.Module._load (internal/modules/cjs/loader.js:533)
    at Module.require (internal/modules/cjs/loader.js:640)
    at require (internal/modules/cjs/helpers.js:20)
    at Object.<anonymous> (/home/yanderella/.config/discordcanary/0.0.67/modules/discord_cloudsync/index.js:2)
    at Object.<anonymous> (/home/yanderella/.config/discordcanary/0.0.67/modules/discord_cloudsync/index.js:30)
    at Module._compile (internal/modules/cjs/loader.js:693)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704)
    at Module.load (internal/modules/cjs/loader.js:602)
    at tryModuleLoad (internal/modules/cjs/loader.js:541)
    at Function.Module._load (internal/modules/cjs/loader.js:533)
    at Module.require (internal/modules/cjs/loader.js:640)
    at require (internal/modules/cjs/helpers.js:20)
    at requireModule (evalmachine.<anonymous>:6)
    at Object.requireModule (/home/yanderella/.config/discordcanary/0.0.67/modules/discord_desktop_core/core.asar/app/discord_native/nativeModules.js:78)
    at Object.requireModule (e3064949dcbe2174224d.js:62)
    at Object.getCloudSync (e3064949dcbe2174224d.js:62)
    at Object.<anonymous> (e3064949dcbe2174224d.js:62)
    at g (e3064949dcbe2174224d.js:135)
    at Generator._invoke (e3064949dcbe2174224d.js:135)
    at Generator.e.(anonymous function) [as next] (https://canary.discordapp.com/assets/e3064949dcbe2174224d.js:135:46996)
    at r (e3064949dcbe2174224d.js:62)
    at e3064949dcbe2174224d.js:62
```

**Comment by aetheryx** [comment]
Does `/usr/share/discord-canary/app/` exist and what files do you see in that folder?

**Comment by ghost** [comment]
> Does `/usr/share/discord-canary/app/` exist and what files do you see in that folder?

There are two files, one is called `index.js`, another one is called `package.json`. `index.js`'s content is this:
```js
require(`/home/yanderella/powercord/injectors/../src/patcher.js`)
```

**Comment by aetheryx** [comment]
Can you run the DiscordCanary executable manually (`/usr/share/discord-canary/DiscordCanary` or `/usr/share/discord-canary/resources/DiscordCanary`) to make sure you're injecting into the same version as what you run, and make sure that the error you sent above is the only error you can see?

**Comment by ghost** [comment]
> Can you run the DiscordCanary executable manually (`/usr/share/discord-canary/DiscordCanary` or `/usr/share/discord-canary/resources/DiscordCanary`) to make sure you're injecting into the same version as what you run, and make sure that the error you sent above is the only error you can see?

I get this:
```
~$ /usr/share/discord-canary/DiscordCanary
DiscordCanary 0.0.67
Starting updater.
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Module install path: /home/yanderella/.config/discordcanary/0.0.67/modules
[Modules] Module installed file path: /home/yanderella/.config/discordcanary/0.0.67/modules/installed.json
[Modules] Module download path: /home/yanderella/.config/discordcanary/0.0.67/modules/pending
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/canary/versions.json
[Modules] No module updates available.

(DiscordCanary:23324): GLib-GIO-CRITICAL **: 18:25:52.193: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
```

**Comment by aetheryx** [comment]
Could you change the contents of `/usr/share/discord-canary/app/index.js` to the following, reboot your client and see if the file was made?
```js
require('fs').writeFileSync('/home/yandarella/test.txt', '');
require(`/home/yanderella/powercord/injectors/../src/patcher.js`)
```

**Comment by ghost** [comment]
> Could you change the contents of `/usr/share/discord-canary/app/index.js` to the following, reboot your client and see if the file was made?
> 
> ```js
> require('fs').writeFileSync('/home/yandarella/test.txt', '');
> require(`/home/yanderella/powercord/injectors/../src/patcher.js`)
> ```

nope, the file wasn't made

**Comment by aetheryx** [comment]
Could you run `ls` in `/usr/share/discord-canary/`?

**Comment by ghost** [comment]
> Could you run `ls` in `/usr/share/discord-canary/`?

```
$ ls
app                     libEGL.so             resources
chrome_100_percent.pak  libffmpeg.so          resources.pak
chrome_200_percent.pak  libGLESv2.so          snapshot_blob.bin
DiscordCanary           libVkICD_mock_icd.so  swiftshader
discord-canary.desktop  locales               v8_context_snapshot.bin
discord.png             natives_blob.bin
icudtl.dat              postinst.sh
```

**Comment by aetheryx** [comment]
try changing `powercord/injectors/linux.js` to return `/usr/share/discord-canary/resources/app` (you should see a file called `app.asar` in the `resources` folder before you start)

**Comment by ghost** [comment]
> try changing `powercord/injectors/linux.js` to return `/usr/share/discord-canary/resources/app` (you should see a file called `app.asar` in the `resources` folder before you start)

Now powercord works, thank you!

**Comment by aetheryx** [comment]
👍 will rename issue to support multiple paths on Linux.

**Comment by a8underscore** [comment]
can you also add support for /usr/lib/discord-canary/
(or an option to specifiy path)
thanks
