### ISSUE TITLE
[Style Manager] Rewrite (kinda)

### ISSUE THREAD

**Issue by cyyynthia** [powercord-org/powercord#81]
I'll update this issue when elements are implemented :)

 - [x] (wont fix) Create a scss function to compile classes (like [this](https://media.discordapp.net/attachments/517348857219383308/538180739968139286/Capture.PNG?width=752&height=450), credits to MasicoreLord#5338) instead of our slow shitty compiler
 - [x] (won't fix) Add an "Export to CSS" function for theme developers who wants support for more than PC
 - [ ] Way easier installation of themes, with the same behaviour as Plugin explorer
 - [x] Support for Stylus
 - [x] Live editor within the client for throwing quick css changes or snippets

## Notes for the theme explorer
For plugins it makes sense to restrict plugins repo, since they need to be written for PC and there is some security concerns. But for themes I would opt for manual add to the eplore themes, but with either an external repo, or a repo in the Powercord org, with external repos for developers who supports more than PC (like BeautifulDiscord) and in the org themes made for PC (with .pc- classes). There is a lot of themes already out and imo it would be more a waste of customization to only allow themes from pc org

**Comment by intrnl** [comment]
Consider supporting Stylus as an alternative preprocessor

**Comment by intrnl** [comment]
Another suggestion would be to make it so that themes can easily override a plugin's styling by having it last.

**Comment by komfluent** [comment]
You should add a keybind to temporarily disable the current theme for like taking a screenshot or something. And make the the keybind customizable. That would be very useful for taking a screenshot for a server that is really sensitive about client mods (hint hint "The Source Code")

**Comment by cyyynthia** [comment]
This is getting addressed in #155

**Comment by ghostlydilemma** [comment]
Idea for StyleManager, be able to give a url-parameter in the manifest and an icon to be displayed left or right to the Powercord Logo
Current Sollution of Customa, without Link:
![grafik](https://user-images.githubusercontent.com/29519722/56472791-62954380-6463-11e9-9a1e-9a89e7f0fcf5.png)
Click on the icon would open the link - could possibly also be visible in the overview of installed themes

**Comment by cyyynthia** [comment]
The main purpose of this issue has been fulfilled with the implementation of QuickCSS
