### ISSUE TITLE
[Feature Request] Double Click to Edit

### ISSUE THREAD

**Issue by SacreBleuXCVII** [powercord-org/powercord#82]
**Describe the feature request**
Allows you to edit a message by double clicking it.

**What Plugin would it be for?**
None, it would be its own plugin.

**Expected behavior**
You double click a message, not the text, and it allows you to edit it without having to click the dropdown and select it.

**Comment by ohlookitsderpy** [comment]
Ported a BetterDiscord plugin that does this, can be found at https://github.com/ohlookitsderpy/pc-doubleclickedit

This issue can now be closed™
