### ISSUE TITLE
[Spotify] Glitchy Seek Bar

### ISSUE THREAD

**Issue by SacreBleuXCVII** [powercord-org/powercord#89]
**Describe the bug**
When trying to click at a specific spot it glitches out and doesn't go there.

**To Reproduce**
Click anywhere on the seek bar instead of dragging it.

**Expected behavior**
It should seek to that specific position.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Discord version: [BUILD INFO] Release Channel: canary, Build Number: 31744

**Comment by 21Joakim** [comment]
This behaviour seems to be caused by [`if (await SpotifyPlayer.pause())`](https://github.com/powercord-org/powercord/blob/v2/src/Powercord/plugins/pc-spotify/Modal/SeekBar.jsx#L47)

**Comment by cyyynthia** [comment]
fixed locally, will push soon
