### ISSUE TITLE
[Feature Request] Right Click for Role ID

### ISSUE THREAD

**Issue by BillsLate** [powercord-org/powercord#91]
**Describe the feature request**
Allows you to get the role id easily

**What Plugin would it be for?**
Its own plugin

**Expected behavior**
Whenever you right click on a role, it gives you the role id

**Comment by cyyynthia** [comment]
Implemented on this commit https://github.com/powercord-org/powercord/commit/a317185c4b515fd6aac52306082f925a82748156
