### ISSUE TITLE
[Feature Request] Custom hastebin uploader

### ISSUE THREAD

**Issue by Kanin** [powercord-org/powercord#98]
**Describe the feature request**
Just a text field on the hastebin plugin that lets you set a custom uploader

**What Plugin would it be for?**
hastebin

**Expected behavior**
Changes where the haste gets sent to

**Comment by aetheryx** [comment]
landed in https://github.com/powercord-org/powercord/commit/df732c945f7a4e1051f15c09f6a244bf960f6e3c
